
export const categories = ["All Categories", "Beauty Parlour", "Medical Aesthetics", "Dermatology", "Cosmetic Surgery"]

export const services = [
  "Botulinum toxins",
  "Dermal fillers",
  "Chemical peels",
  "Microneedling",
  "Skin rejuvenation",
  "Facial treatments",
]

// Types for a visx-friendly boxplot + overlays
export interface BoxStats {
  min: number
  q1: number
  median: number
  q3: number
  max: number
  mean: number
}

export interface ItemMeta {
  label?: string
  weighted_score: number
  confidence: number
  num_mentions: number
  top_sentence: string[]
}

export interface BoxPlotDatum {
  // Short key for internal reference (matches your stats keys)
  key: string
  // Human-readable label for display (matches your provided display names)
  label: string
  stats: BoxStats
  item: ItemMeta
}

// Combined data: quartiles/mean + item weighted score per category


// item: {
//   weighted_score: 0,
//   confidence: 0,
//   num_mentions: 0,
//   top_sentence: [],
// }

export const boxplotDatas_clinic: BoxPlotDatum[] = [
  {
    key: "Clinical",
    label: "Clinical Expertise",
    stats: {
      min: 0,
      q1: 4.343109428882599,
      median: 17.93204963207245,
      q3: 44.27363693714142,
      max: 124.64579641819,
      mean: 26.68306371202295,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },

  {
    key: "Communication",
    label: "Communication",
    stats: {
      min: 0,
      q1: 9.218587279319763,
      median: 23.909608349204063,
      q3: 48.75052556395531,
      max: 100.55664733052254,
      mean: 30.95581457107903,
    },
    item: {
      weighted_score: 25.74636533856392,
      confidence: 5.309156835079193,
      num_mentions: 20,
      top_sentence: [],
    },
  },
  {
    key: "Treatment",
    label: "Treatment Results",
    stats: {
      min: 0,
      q1: 7.847011610865593,
      median: 30.68303018808365,
      q3: 83.74123051762581,
      max: 152.68114566802979,
      mean: 46.669279678138764,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Bedside",
    label: "Bedside Manner",
    stats: {
      min: 0,
      q1: 15.70406012237072,
      median: 39.926849976181984,
      q3: 74.87227752804756,
      max: 136.73264637589455,
      mean: 45.651995214629935,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Trust",
    label: "Trust & Safety",
    stats: {
      min: 0,
      q1: 11.094762831926346,
      median: 31.926841288805008,
      q3: 64.03341848403215,
      max: 109.38527762889862,
      mean: 38.18532405621502,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Environment",
    label: "Environment",
    stats: {
      min: 0,
      q1: 7.066807150840759,
      median: 26.941265910863876,
      q3: 70.54585747420788,
      max: 146.94780379533768,
      mean: 40.320863753429435,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Personalization",
    label: "Personalization",
    stats: {
      min: 0,
      q1: 13.11387911438942,
      median: 31.981745064258575,
      q3: 61.87361553311348,
      max: 111.4104674756527,
      mean: 37.33001251560283,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "PostCare",
    label: "Post-Care",
    stats: {
      min: 0,
      q1: 15.826747864484787,
      median: 40.348722860217094,
      q3: 91.1517734080553,
      max: 140.9870870411396,
      mean: 50.219614097915326,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Professionalism",
    label: "Professionalism",
    stats: {
      min: 0,
      q1: 8.84803507477045,
      median: 23.283715471625328,
      q3: 44.61786046624184,
      max: 105.66882207989693,
      mean: 29.27594122807106,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Staff",
    label: "Staff Support",
    stats: {
      min: 0,
      q1: 5.289367660880089,
      median: 21.78466185927391,
      q3: 58.919208496809006,
      max: 154.31525766849518,
      mean: 34.88372503241798,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Value",
    label: "Value & Transparency",
    stats: {
      min: 0,
      q1: 0,
      median: 1.60221166908741,
      q3: 4.535106718540192,
      max: 35.74694335460663,
      mean: 3.00953234185973,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Pain",
    label: "Pain Management & Comfort",
    stats: {
      min: 0,
      q1: 15.595480725169182,
      median: 41.59490205347538,
      q3: 72.56548549979925,
      max: 136.8950954079628,
      mean: 45.21396052136839,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Anxiety",
    label: "Anxiety & Nervousness Management",
    stats: {
      min: 0,
      q1: 13.221703432500362,
      median: 35.63545674085617,
      q3: 63.73773954808712,
      max: 121.96247562766075,
      mean: 39.47238837491231,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Booking",
    label: "Booking & Accessibility",
    stats: {
      min: 0,
      q1: 3.325166143476963,
      median: 9.564984440803528,
      q3: 19.93670206516981,
      max: 102.04850390553474,
      mean: 15.357905016299263,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Honesty",
    label: "Honesty & Realistic Expectations",
    stats: {
      min: 0,
      q1: 3.8958152011036873,
      median: 13.050354719161987,
      q3: 25.834566242992878,
      max: 59.85129103064537,
      mean: 16.33952630527941,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
  {
    key: "Longterm",
    label: "Long-term Relationship & Loyalty",
    stats: {
      min: 0,
      q1: 15.221665054559708,
      median: 40.93294680118561,
      q3: 77.87621986120939,
      max: 127.00567960739136,
      mean: 46.249700638343135,
    },
    item: {
      weighted_score: 0,
      confidence: 0,
      num_mentions: 0,
      top_sentence: [],
    },
  },
]

export const search_categories: string[] = [
"Skin care clinic",
"Plastic surgery clinic",
"Medical spa",
"Women's health clinic",
"Laser hair removal service",
"Doctor",
"Hair replacement service",
"Dermatologist",
"Cosmetic surgeon",
"Plastic surgeon",
"Beauty Parlour",
"Hair transplantation clinic",
"Hair removal service",
"Health consultant",
"Esthetics service",
"Nurse practitioner",
"Health and beauty shop",
"Medical clinic",
"Housing complex",
"Dental clinic",
"Nursing home",
"Specialized clinic",
"Cosmetics industry",
"Hairdresser",
"Registered general nurse",
"Hair salon",
"Office space rental agency",
"Cosmetic dentist",
"Dentist",
"Orthopedic clinic",
"Medical group",
"Permanent make-up clinic",
"Beautician",
"Wellness center",
]


export const brands = [" /  (Mortara accessory)",
"3B Scientific",
"3Dose",
"3M",
"3M Aura",
"3M Littmann",
"3M Micropore",
"3M Tegaderm",
"3M\u2122",
"3M\u2122 Aura\u2122",
"3M\u2122 Micropore\u2122 Surgical Tape",
"3S Healthcare",
"4EVER",
"5-Amino-1MQ",
"Abeba",
"ACE MEDICAL",
"Aciclovir",
"ACM Laboratoire Dermatologique",
"Acnecide",
"Actichlor Plus",
"Adcortyl",
"Adrenaline (Epinephrine) 1mg/ml (1:1000) solution for injection (ampoule)",
"AeroWipe",
"AESHILO\u00ae",
"aesPlla",
"Aessoa",
"AestheFill",
"Aesthetics RX Pharma",
"AestheticsRx",
"AestheticsRX Pharma",
"Aesthipharma",
"Aesthipharma (multi-brand pack: Hyalmass, Puri, Lemon Bottle and others)",
"AETER / AeterDerm",
"Aeterderm",
"AETERDERM PURI COLL Rh",
"Afterderm (Puri)",
"AfterMED Lips",
"Agarwood Oil Natural Identical",
"AHK-Cu",
"AICAR",
"Aklief",
"Alaris",
"ALASTIN",
"ALASTIN Skincare",
"Albert Waeschle",
"Alexandra",
"Aliaxin",
"Alidya",
"Alkotip",
"Alli",
"Alluzience",
"Alma",
"Alma Harmony XL PRO",
"Alma Lasers",
"Amais\u00e9 cosmetics",
"Ameela Eyes",
"Ameela Face",
"Ameela Rejuvenation",
"AMI Eyes (Amieyes)",
"Ami Plus X",
"AMI Tone Up",
"AMiKO",
"Amoxicillin 125 mg/5 ml Powder for Oral Suspension Sugar Free",
"Amoxicillin 250 mg/5 ml Powder for Oral Suspension Sugar Free",
"Amoxicillin Sugar Free 250 mg/5 ml",
"Anagel",
"Anua",
"Anvil",
"AOD9604",
"Apilus",
"Apriline",
"Aqualyx",
"ARES",
"ARES (Advanced Regenerative Esthetics Solution)",
"Arielle",
"Arthrex / Drucker",
"Arthrex ACP",
"ASCE+",
"ASCE+ (ASCEplus HRLV)",
"Astanza",
"Aurelia",
"Aurelia Amazing",
"Aurelia Gloves",
"Aurelia Robust Plus",
"Aurora",
"Autoject\u00ae2",
"Av\u00e8ne",
"AVAH Fill",
"Aveeno",
"Avoca",
"AW Select",
"AW3",
"Azo",
"Azo / Azowipe",
"Azo Universal",
"Azowipe",
"Azowipe / Azo\u2122 Wipette",
"Azzalure",
"B. Braun",
"B. Braun Intrafix",
"B. Braun Intrafix SafeSet",
"B. Braun Omniflush",
"B.I.G. Bone Injection Gun (Adult)",
"BAC-STAT",
"Bacteriostatic 0.9%",
"Bacteriostatic Water",
"Baldan Group",
"Bangota",
"Barbicide",
"Barco Essentials",
"Barco One",
"BARDEX I.C.",
"Baxter",
"Baxter (Easyflow)",
"Baxter Buretrol",
"Baxter Healthcare",
"BCN",
"BD",
"BD (Becton Dickinson)",
"BD (Becton, Dickinson and Company)",
"BD BodyGuard\u2122 T",
"BD Emerald",
"BD Insyte",
"BD Insyte\u2122 Autoguard\u2122 BC Pro",
"BD Insyte-W\u2122",
"BD Integra\u2122",
"BD Luer-Lok\u2122",
"BD Micro-Fine",
"BD Micro-Fine\u2122 Plus",
"BD Micro-Fine+ (BD - Becton Dickinson)",
"BD Microlance",
"BD Microlance 3",
"BD Microtainer",
"BD Neoflon Pro",
"BD Nexiva",
"BD Nokor",
"BD Oral Dispensing Syringe",
"BD Plastipak / BD Microlance 3",
"BD Plastipak\u2122 / BD Microlance\u2122 3",
"BD Quincke",
"BD Safe-Clip",
"BD SafetyGlide",
"BD Saf-T-Intima",
"BD Saf-T-Intima\u2122",
"BD Vacutainer",
"BD Vacutainer Safety-Lok",
"BD Veca-C\u2122",
"BD Venflon Pro Safety\u2122",
"BD Viva",
"BD\u2122 Quincke Spinal Needle",
"Beauty of Joseon",
"Becton Dickinson",
"Becton Dickinson (BD)",
"Behrens",
"Belkyra / Kybella",
"Bellafill",
"Bellamianta",
"Bell's",
"Belotero",
"Benzylpenicillin sodium",
"BienPeel",
"Biocyte",
"Biodance",
"Biodance (AP Radiant Vita branding by Aesthipharma)",
"Biodance (distributed under AP / Aesthipharma branding)",
"Biodance (marketed as AP Hydro Cera-Nol Face Mask by Aesthipharma)",
"Bioderma",
"BioReHydra",
"BioReHydra (BioReTherapy line, CMed Aesthetics)",
"BioReLift",
"BioReLift (BioReTherapy line by CMed Aesthetics)",
"BioRePeel / CMed Aesthetics",
"BioRePeelCl3",
"BioRePeelCl3 BODY",
"Bios Square",
"Biotec",
"Biotech",
"Biotine 0.5%",
"Biotine Bayer",
"BIRKENSTOCK",
"Blackrock",
"Blue Dot",
"Blue Dot (Crest Vomit)",
"Bocouture",
"Bodyguards GL897 (Polyco)",
"BOTOX",
"Botulax",
"Brandon Medical",
"Brandon Medical Astralite",
"Brandon Medical Astralite eLite",
"Braun",
"Brightwell Dispensers",
"Brimonidine Tartrate 0.2% w/v Eye Drops",
"Brimonidine Tartrate 2 mg/ml Eye Drops, Solution",
"Bristol Maid",
"British Institute of Lasers",
"British Nova",
"BTL",
"BTL EMTONE",
"BTL EXILIS ULTRA 360",
"Bunzl Catering Supplies",
"Bunzl Clean (Ounce-A-Matic / Pelican Pump)",
"BYONIK CONCUR",
"Calcium Gluconate",
"Calypso",
"Cambderm",
"Cameco",
"Candela",
"Cardiogen",
"Carell (Clinell Bed Bath)",
"CarePoint",
"CARESITE",
"Caresite\u00ae (B. Braun)",
"Cartalax",
"Cath-it",
"Cath-it Acute Plus",
"Cederroth",
"Cellenis",
"Cerebrolysin",
"Cernevit",
"Cetaphil",
"Cetraben",
"Cherokee",
"Cherokee Code Happy",
"Cherokee Flexibles",
"Cherokee Luxe",
"Cherokee Luxe (Cherokee Uniforms)",
"Cherokee Revolution",
"Cherokee Workwear Originals",
"Chicopee J-Cloth Plus",
"Cincelar Plus",
"CLATUU",
"Cleanall (Clinell / GAMA Healthcare)",
"Cleanline",
"CleanWorks",
"Cleenol",
"Cleenol Envirological",
"Cleenol Senses",
"Clinell",
"Clinell (Carell Bed Bath)",
"Clinell (Carell Body Care)",
"Clinell (Carell Patient Wipes)",
"Clinell (Carell Refreshing Patient Wipes)",
"Clinell (HEXI PREP)",
"Clinell (Rediair)",
"Clinell Cleanall",
"Clinic Consumables",
"Clinipro",
"Clinisafe (Vernacare)",
"Clinisept+",
"Clinisoothe+",
"Clothing & Scrubs",
"Co-amoxiclav",
"COAST",
"Cobalin-H",
"Co-Clens",
"Cocoon Medical",
"Code Happy",
"Code Happy (by Cherokee)",
"Code Happy (Cherokee / Strategic Partners)",
"Code Happy (Cherokee / Work In Style)",
"Code Happy (Cherokee)",
"Code Happy by Cherokee",
"Cojent",
"Collagen Golden Eye Mask",
"Collagen Night Wrapping Mask",
"Conti",
"Conti (Vernacare)",
"Conti\u00ae",
"Continu",
"Contiplex Tuohy Ultra 360 (B. Braun)",
"Cool Sculpting",
"CoolTherm",
"Coolview",
"Cosmopro",
"Cosmopro Cosmed",
"Cosmopro Hikari",
"COSRX",
"Countourel",
"Countourel (by Croma-Pharma)",
"Coup d'\u00c9clat (by Laboratoires Asepta)",
"COVERMARK",
"Croma",
"Croma (PolyPhil / PhilArt range)",
"Croma (SAYPHA / Croma Skincare range)",
"CROMA / PhilArt",
"Croma / TSK",
"Croma PhilArt / PolyPhil",
"Cromptons",
"Crystal Carboxy",
"CRYSTAL DE LABORATOIRES COLLAGENA",
"Crystal Healer",
"Crystal Hydro",
"CRYSTALSMOOTH\u00ae by macom\u00ae",
"Curacorn\u00ae",
"Cutan",
"Cutan (Deb / SC Johnson Professional)",
"Cutan (SC Johnson Professional)",
"Cutan / SC Johnson Professional",
"Cutera",
"Cutera truSculpt\u00ae flex / truFlex\u00ae platform",
"Cutisoft",
"Cynosure",
"Cytocare",
"Cytolax",
"D\u00e9esse PRO",
"Daniels",
"Daniels Healthcare (POUDS\u00ae)",
"DARAY",
"DAXXIFY",
"Daylong Actinica (Galderma)",
"Daylong Extreme (Galderma / Spirig)",
"DEB",
"Deb / SC Johnson Professional",
"Deb Cutan",
"Deb InstantFOAM Complete (SC Johnson Professional)",
"DEFINISSE",
"DEFINISSE (RELIFE / Menarini Group)",
"Deka",
"Deka/Lynton",
"Delph Sun Care",
"DeneB",
"Dependaplast",
"Derma Filler Ltd",
"Derma Filler Ltd (research peptide line)",
"Dermaceutic",
"Dermaheal",
"Dermalactives",
"Dermalax",
"Dermalux",
"Dermapen",
"DermapenWorld\u2122",
"Dermaqual",
"Dermaren",
"Dermaroller",
"Derma-Seal",
"Dermastir",
"Dermica",
"Dermol",
"Desirial",
"Deso",
"Dibase",
"DIBASE (colecalciferol 300,000 IU/ml solution for injection)",
"Dickies",
"Dispoderm",
"DISPOSApak",
"DIVES MED",
"DIYNAD+",
"Doctor Needle 64 (DN64)",
"Doherty",
"Dominique",
"Doublebase",
"Doxycycline (generic)",
"Doxycycline 100mg Capsules",
"Dp Dermaceuticals",
"Dp Dermaceuticals (DermapenWorld)",
"Dr Muller",
"DR SMITH EXPERT",
"Dr. Althea",
"Dr. ArJo",
"Dr. CYJ Hair Filler",
"Dr. Lipo+",
"Dr. Lipo+ V",
"Dr. Pen",
"Dr. Pen / BioPen",
"Dr.Jart+",
"Dressit",
"DTS",
"Durolane",
"Dysport",
"e.p.t.q.",
"E45",
"EasyPoint\u00ae",
"Eau Thermale Av\u00e8ne",
"Echonia",
"Ecolab",
"Ecolab (Actichlor range)",
"Ecolla",
"EdenCleen",
"Efracea",
"EJAL 40",
"Ela (Safety Jogger Professional / Oxypas line)",
"ELASTY",
"Elaxen PN",
"Elite Bags",
"Elite Bags (CONBIO'S / CONBIOS)",
"ELLANS\u00c9",
"Elleste Duet",
"Elleste Solo",
"Eloquence",
"Elure",
"Elysion Pro",
"Embryolisse",
"EMLA",
"ENEKA PRO",
"ENEOMEY",
"Energist",
"Energizer",
"Enerpeel",
"Epaderm",
"Epimax",
"EpiPen",
"Epitique (e.p.t.q.)",
"Ergocalciferol",
"Essentials",
"Estring",
"ETHILON",
"Eucerin",
"Euro-Gen",
"Euro-Gen Peptides",
"Evolution (Safety First Aid Group)",
"Evorel",
"Exam Light III\u2122",
"Exchange Supplies",
"Exilis Ultra 360",
"EXO|E",
"Exoblanc",
"Exocean",
"Exojuv",
"Extra",
"Exuviance",
"FADE",
"Famotidine (generic)",
"Fibrovein",
"Fifty:50",
"Fillers Direct",
"FILLMED",
"FILLMED (by Filorga)",
"FILLMED (formerly Filorga Medical)",
"FILLMED (Skin Perfusion)",
"FILLMED ART FILLER",
"FILLMED NCTF 135HA",
"FILLMED Skin Perfusion",
"Filorga",
"Finasteride (generic)",
"Flawless",
"Fleek",
"Flexitol",
"Flowflex",
"Flucloxacillin Sugar Free",
"FMC (Fine Micro Cannula)",
"FMC Fine Micro Cannulae (FMC)",
"FMS (Fine Micro Syringe)",
"Forceval",
"Fotona",
"Fotona Dualis",
"Fucidin",
"Fusidic Acid",
"Fusidic acid 20 mg/g cream",
"GBO (Greiner Bio-One)",
"GBO (Greiner Bio-One) VACUETTE",
"Genefill",
"Geneo X",
"GENERIC",
"Generic (unbranded phenoxymethylpenicillin / Penicillin V)",
"Generic / depends on supplier",
"Generic / First-Aid PPE",
"Generic / Medisave",
"Generic / Pharmaceutical Grade",
"Generic / unspecified",
"Generic / Various (e.g. Valoid, Marezine)",
"Generic / various suppliers (e.g. Synergy Health, Vernacare, Premier, etc.)",
"Generic \u201cSharp Needles\u201d (OEM/contract manufacturer)",
"Generic aciclovir 5% cream",
"Generic Amoxicillin (brands may vary)",
"Generic Azithromycin",
"Generic cefalexin",
"Generic cefotaxime",
"Generic chlorphenamine maleate (brands may vary)",
"Generic ciprofloxacin",
"Generic clarithromycin",
"Generic cosmetic peptide (AHK / Tripeptide-3)",
"Generic Fexofenadine (e.g. Allevia and other generics)",
"Generic Flucloxacillin",
"Generic Flucloxacillin (Alliance Healthcare generic line)",
"Generic Fluconazole",
"Generic latex examination gloves",
"Generic Lidocaine Hydrochloride",
"Generic low-dose aspirin (brands may vary)",
"Generic Metronidazole 200mg Tablets BP",
"Generic Metronidazole BP",
"Generic Prednisolone",
"Generic Propranolol 40mg Tablets",
"Generic Type IIR Surgical Mask",
"Genticin (generic gentamicin injection)",
"Genticin / generic gentamicin",
"Genticin / Generic Gentamicin 0.3%",
"GFCell (GFC Exo PN Kit)",
"GHRP-6 & CJC-1295 DAC Peptide Combination",
"GHRP-6 & Ipamorelin Peptide Combination",
"Gioluxe",
"Glamox",
"Glamox (Luxo)",
"Glamox Luxo",
"Glitterbels",
"Global",
"GlucoRx",
"GlucoRx CarePoint Ultra",
"GlucoRx FinePoint",
"Glutanex",
"Godgel",
"GOJO",
"GOJO SHIELD",
"Goldfill",
"Gonadorelin",
"GOURI",
"Gowllands",
"Granions",
"Green Series IV",
"Greiner Bio-One",
"Gripper",
"Gripper Micro",
"Gripper Plus\u2122",
"GV Health",
"GV Health (Polycare range)",
"GVS",
"Hair Bloom",
"Handanhy (HY)",
"Handanhy (model HY8220, marketed by HY / HY Medical Limited)",
"Handsafe",
"HARMONI",
"Harmony XL Pro",
"HArmonyCa",
"Haz-Tab",
"HEINE",
"Helapet",
"Heliocare",
"Heliocare 360\u00b0",
"Hepsal / Heparin Sodium 10 I.U./ml Flushing Solution",
"Hibiscrub",
"HipTok",
"Hive",
"HP Cell Vitaran",
"HSE Compliant",
"HYAcorp",
"Hyafilia",
"Hyalace",
"Hyalase",
"HYALMASS",
"Hyalu DNA Tox",
"HYALUAL",
"HYALUAL Xela Rederm",
"Hyaluronidase (generic, brand-unspecified)",
"Hyaluronidase 1500 IU",
"Hyamira",
"Hyaron",
"Hydra",
"Hydrafacial",
"Hydrex Pink",
"Hydromol",
"Hydroxocobalamin",
"Hydroxocobalamin (Generic Vitamin B12)",
"Hydroxocobalamin (Vitamin B12)",
"Hygea",
"HypaClean",
"HypaCool",
"HypaGel",
"Ice Pack",
"ICE STORM",
"Iconic Bronze",
"IDS",
"IGF-1 DES",
"IGF-1 LR3",
"iLLUMA",
"iLLUMA Luna",
"Image Coloraction",
"INEX AESTHETIC GROUP",
"INEX AESTHETIC GROUP - REPEARL",
"INEX AESTHETIC GROUP (Beauty Bio Cell Mask)",
"Infection Control",
"INFINI",
"INFINI Premium Filler",
"Infusomat\u00ae / B. Braun",
"ingo-man\u00ae classic",
"Injekt",
"Injekt\u00ae-F",
"Inmode",
"Innoaesthetics",
"INNOAESTHETICS (INNO-DERMA)",
"INNOAESTHETICS \u2013 INNO-DERMA",
"Innoderm Hyalu Serum 2.3 (Bio Logica range)",
"INNO-DERMA",
"INNO-EXFO MANDELAGE",
"Innovatouch Cosmetic",
"Institut Esthederm",
"Institut Esthederm (OSMOCLEAN)",
"Instrapac",
"Insupen",
"Interlink",
"Intersurgical",
"Intrafix SafeSet",
"Intraline",
"IntraLipo",
"Introcan Safety",
"Iopidine",
"Irripod",
"iS Clinical",
"ISDINCEUTICS",
"Isdinceutics (ISDIN)",
"Jalupro",
"JBP",
"JBP (Japan Bio Products)",
"JBP Nanoneedle",
"Johnson & Johnson",
"Juma",
"JUV\u00c9DERM (SKINVIVE)",
"Juv\u00e9derm",
"Juvederm",
"JUVELOOK",
"Kairax",
"Kamilane",
"Kapoff",
"Karisma",
"Katrin",
"KELO-COTE",
"Kenalog",
"Key Scrubs (by Work in Style)",
"Kiara Reju",
"KleenSpec",
"KleenSpec 590 Series Premium",
"KLmedi / Extra",
"Koolpak",
"Koolpak (sold as Sure Thermal / Medisave own-brand in some listings)",
"Kr\u00e8me",
"La Roche-Posay",
"Labcold",
"Laboratoire ACM",
"Laboratoire Revitacare",
"Lanez Skin",
"Lanluma",
"Lapiena",
"Laser Vision",
"Laxido Orange",
"Ledlenser",
"Lemon Bottle",
"Lemon Fill",
"LemonBottle",
"LENISNA",
"Lenzetto",
"Letybo",
"Leukoplast",
"Leuphasyl",
"Levair",
"L-Glutathione",
"LHM",
"LIFSkin",
"Lift (Cleenol)",
"Linerase",
"Lipfl\u00e9",
"Lipo Lab",
"Lipo Lax",
"Lipo Vela",
"Lipofirm Pro",
"Lipopeptide (Biopeptide EL)",
"LMX4",
"Lojer",
"Longevha",
"Loniten",
"Loratadine (generic)",
"Lotil",
"Love Cosmedical",
"LOVEUP",
"LPG",
"LPG Health",
"Lumenis",
"Lumenis / Pollogen (LipoFirm MED)",
"Lumenis LightSheer",
"Lumenus",
"Lumifil",
"Lumigan",
"LUMINESCENS",
"Lumi-PN",
"LUMI-PN (by LUMI-PRO UK)",
"LUMI-PN / LumiPro",
"LUMI-PRO",
"Luna Glow",
"LUNA Q",
"Lust Lip Pigments",
"Luxamed",
"LuxFill",
"Luxo",
"Luxo (Glamox)",
"Lynton",
"Lynton Focus Dual",
"MACOM",
"Macrolane",
"MAGIC NEEDLE",
"Magicalift",
"Magnesium Sulfate 50%w/v Solution for Injection (generic)",
"Magnesium Sulphate 50% Solution for Injection (generic)",
"MaiLi Define",
"MaiLi Extreme",
"MaiLi Precise",
"MaiLi Volume",
"Marine Beauty Collagen",
"Marine Radiance",
"Martindale Pharma (an Ethypharm Group Company)",
"maskology (+maskology)",
"Mast (Dragonhawk)",
"Mastelli",
"Mastelli NEW Gyn",
"Masterplast",
"Matrixyl",
"Maxitrol",
"McKinnon Medical",
"MedAesthetics",
"Medi Derma-S",
"Medicina",
"Medik8",
"Medipal",
"Medipal PAL TX",
"Medipal PalTX",
"Medi-Plinth",
"MediPro",
"Medisanitize",
"Medisanitize (via Medisave UK Ltd)",
"Medisanitize / Medisave UK",
"Medisave",
"Medisave Professional",
"Medisco",
"Medisco (by Stayve)",
"Melanostatin DM",
"Mepore",
"Merz",
"Merz Aesthetics (Radiesse+)",
"Mesbio Needle (Needle Concept)",
"MesmerEyez",
"mesoestetic",
"Mesoft",
"Mesoheal",
"MESOHEAL DUAL",
"Mesoheal Orchid Glow",
"Mesoheal Pink Glow",
"Mesoheal\u00ae Amber Glow",
"MESOHEAL+",
"Mesoram",
"MESORAM plate",
"Mesorelle (Meso-relle / Mesorelle\u00ae)",
"Microdot",
"Microdot Droplet",
"Micro-Fine\u2122",
"Micropore (3M\u2122 Micropore\u2122 Medical/Surgical Tape)",
"Microsafe",
"mikrozid\u00ae (Sch\u00fclke)",
"Millex-LG",
"Milton",
"MINERVA",
"Mini-Spike",
"Minoxidil",
"MINT Fill",
"MIP",
"MISFILL+ Baby Face",
"MISSMITO",
"MKL Green Nature",
"Monalisa",
"Monovisc",
"Mounjaro",
"Mounjaro (Tirzepatide)",
"Multiple (PRO Handcare / Modular / Generic pouch dispenser families)",
"Multiple manufacturers (ENFit-compatible straws)",
"Multisorb",
"Mysimba",
"NAD+",
"NAD+ (Vitamin Injections London)",
"NAD+ AT HOME",
"Nanopass",
"Naomi Rose",
"Naseptin",
"Natural Plant",
"Natural-Meso",
"Neauvia",
"Neauvia Intense Rose",
"Nebido",
"Needle-Pro EDGE",
"Nellcor",
"Nelsons Arnicare",
"Neofound",
"Neofound & Peppermint Peel",
"Neofound (by Love Cosmedical)",
"Neofound (Love Cosmedical)",
"Neofound EXO",
"Neofound Whitening",
"Neostrata",
"NeoStrata Enlighten",
"NEOSTRATA ProSystem",
"Neuramis",
"NEURAMIS\u00ae",
"NeuroBloc",
"Nevershare",
"NEWEST One",
"NEWEST\u00ae",
"NewGyn",
"NewGyn\u00ae",
"NEXA",
"Nexfill",
"N-Finders",
"N-Finders N-COG",
"N-Finders RE:Thread",
"NHCO Nutrition",
"Nilaqua",
"NIO Adult\u2122",
"NIO Paediatric\u2122 (NIO-P)",
"Niton Tactical",
"Niton999",
"NIVEA",
"NIVEA SUN",
"N-lite",
"NMN Bottle",
"Not Listed",
"Not publicly listed",
"Not publicly listed (sold by Medisave and multiple workwear retailers)",
"Not publicly listed (sold under the chemical/INCI name \u201cAcetyl Hexapeptide-3 (Argireline)\u201d)",
"Not publicly listed (supplier SKU CON\u2011279 at Two Face Aesthetics)",
"Not specified",
"Novo Nordisk",
"Nucleofill",
"Nucleofill (Promoitalia)",
"Nucleoskin",
"Nurse It",
"NUXE",
"Nytraguard",
"Observ",
"octenisan",
"OEMINE",
"Oestrogel",
"Oilatum",
"Olidia",
"Omnifix",
"Omnifix NRFit",
"Omnifix\u00ae-F",
"Omnitex",
"OMRON",
"OneFill",
"ONSET PRP",
"OptiLube Zero",
"Ortholife",
"ORTHOVISC",
"OUYE Deep Plus",
"OUYE Fine Plus",
"OUYE SubQ Plus",
"Ovestin",
"Owen Mumford",
"Oxypas",
"Oxypas (Safety Jogger Professional)",
"Oxytrol for Women",
"Ozempic",
"Pabrinex",
"Pabrinex / Vitamin B&C Intravenous High Potency",
"Pabrinex / Vitamin B&C Intravenous High Potency (generic)",
"Pabrinex / Vitamin B&C IV High Potency",
"Pascorbin / Ascorbic Acid Pascoe",
"PDI Easy Screen",
"PDI Hygea",
"PDI Sani-Cloth",
"PDI Sani-Cloth AF Universal",
"PDI Sani-Cloth AF\u00b3",
"PDI Sani-Cloth Chlor",
"PDO",
"Pellev\u00e9",
"Pennine Healthcare Oppo-Cath",
"Peppermint Peel",
"Peptide Sciences",
"Perasafe",
"Perfect Line",
"Perfectha",
"Performer Premier",
"Perma",
"Perma Blend Luxe",
"permaICE",
"Pharma-Aesthetic (Pharmacos Supplies)",
"PhilArt (by Croma-Pharma)",
"Physicool",
"Physioskin",
"PicoIris",
"Pine Bottle",
"Placentor",
"Placentor V\u00e9g\u00e9tal",
"Plasma Pen Ulta",
"Plejuv",
"Plenhyage XL",
"PLEXR",
"Plexr Plus",
"Plinest",
"Plinest Fast",
"Plinest Newest",
"Plinest One",
"Plinth 2000",
"Plinth 2000 / Plinth Medical",
"Plinth Medical",
"Plinth Medical (Kirton Task Chair line)",
"Plinth Medical (Plinth 2000)",
"PLLACELL",
"Pluryal",
"Pluryal Mesoline",
"PMMA (Artefill/Bellafill-type composition \u2013 grey-market buttock kit)",
"Podopro",
"Polaris",
"Pollogen",
"PolyPhil Next (by Croma-Pharma)",
"POMEROY",
"Precision",
"Premier",
"Premier / Instraspec",
"Premier Healthcare Excellence",
"Premier Med",
"Premier Performer",
"Premier Prestige",
"PRESEPT",
"Primelase",
"PRIORI",
"Pristine",
"Pristine Hygiene",
"Pro Hydro",
"PRO-Breathe MS",
"Profhilo",
"Profhilo Haenkenium",
"Profhilo Structura",
"Promax",
"Promoitalia",
"Prostap SR DCS",
"Prostrolane",
"Prostrolane Natural B",
"Protect 360\u00b0 (Sani Professional)",
"PROTOCOL",
"proto-col",
"Pro-tocol",
"Proto-col (marketed as Protocol within DD Group nutraceuticals)",
"Proto-col (Protocol range via DD Group/Med-fx)",
"Proto-col (Protocol range)",
"Protocol (proto-col)",
"Proto-col Osteo+ (marketed via Protocol)",
"proto-col Radiance Collagen",
"Proto-col Skin (Protocol)",
"Provita",
"Provita Series 1",
"PRP PURE",
"PRP-LAB (European model)",
"Purasomes",
"Pure Eyes",
"Pure Pro",
"Purell",
"PureSkin",
"Puri (AETERDERM PURI EYES)",
"Puri HiLo PN",
"Puri Lips",
"Purifide",
"Qlicksmart",
"Qlicksmart BladeFlask EVO",
"Quanta System",
"Quatron",
"Quench",
"Radara",
"Radiesse",
"Radiesse \u2013 Merz Pharmaceuticals",
"Rainbow Thread",
"RE:PRIMA",
"Readiwipes",
"Rebotec",
"Regatta",
"Regenovue",
"Regenyal",
"Rejeunesse",
"Rejuran",
"Relfydess",
"Relfydess (relabotulinumtoxinA, botulinum toxin type A)",
"Relief",
"Relief (Reliance Medical)",
"Relief Plus",
"RELIFE (Menarini Group)",
"Reliject (Reliance Medical)",
"Relitape (Reliance Medical)",
"Reliwipe (Reliance Medical)",
"ReMedium",
"Repadern PN",
"REPEARL (INEX AESTHETIC GROUP)",
"Restylane",
"Retatrutide",
"Revanesse Contour+",
"Revanesse Kiss+",
"Revanesse Outline+",
"Revanesse Pure+",
"Revanesse Ultra+",
"Reversal",
"ReversHA",
"Revitacare",
"Revitafill Xtra",
"RevitaLash",
"RevitaLash Cosmetics",
"Revitrane",
"Revofil",
"Revofil Aquashine",
"Revofil Aquashine PTX",
"Revolax",
"REVS",
"REVS PRO32",
"Ribeskin",
"Richelet",
"Richesse",
"Riester",
"Robert Scott",
"Robinsons",
"Rocialle",
"Rocialle EcoRange",
"Rosy",
"ROUGJ",
"RRS",
"RRS (Aesthetic Dermal)",
"RRS / Aesthetic Dermal",
"Rumi",
"Russell PneumoFix",
"Rybelsus",
"Safe Snap",
"Safecare",
"Safeflow",
"Safety First Aid",
"Safety Jogger",
"Safety Jogger Morris",
"Safety Jogger Professional",
"Safety Jogger Professional (Elis O2)",
"Safety Jogger Professional (Oxypas Eliane)",
"Safety Jogger Professional (Oxypas James range)",
"Safety Jogger Professional (Oxypas)",
"SafetyGel",
"Safety-Multifly",
"Salon System / Just Wax",
"SAM IO",
"Sanisafe 4C",
"Sanitez",
"Sanlivna",
"Sanos",
"Sant\u00e9 Verte",
"Sarstedt",
"Savlon",
"Saxenda",
"Saypha (by Croma)",
"Scandonest\u00ae",
"S-Cath\u2122 (Mediplus)",
"Sculpt Pro",
"Sculptra\u00ae",
"SDNA",
"seca",
"SEERS Medical",
"Selden",
"Selden Select",
"Select",
"Semaglutide",
"Semaglutide (active pharmaceutical ingredient)",
"sempercare\u00ae velvet (Sempermed)",
"Senses",
"Septodont",
"Seventy Hyal",
"Sharpaks",
"Sharplight",
"Sharpsafe",
"Sharpsafe\u00ae",
"SHARPSGUARD",
"SHARPSGUARD\u00ae",
"Sheffmed",
"Shermond",
"Silex",
"Silhouette Soft",
"Silkann",
"Simple Solution",
"Simply Protect",
"Singderm",
"SISSEL",
"Skechers",
"Skechers (by Barco)",
"Skin Needle",
"SkinCeuticals",
"Skinfill",
"SkinFill (Promoitalia / Promoitalia Medical Aesthetics)",
"SkinFill (Promoitalia)",
"Skinoren",
"SkinPen\u00ae",
"Skyncare",
"Smiths Medical",
"S-Monovette\u00ae (Sarstedt)",
"SoChlor",
"Sodium Chloride 0.9% (Saline)",
"Sofiderm",
"Softalind",
"Softaskin",
"SoftFil",
"Softfill",
"Sol\u2011Care",
"Sol-Care",
"Solgar",
"SOL-M",
"Sol-M\u2122",
"Solta Medical",
"Some By Mi",
"Soprano",
"Soprano Platinum",
"Sosum",
"SP Services",
"Spectricept",
"Spirigel",
"StarFill",
"Stayve",
"Sterican\u00ae",
"Stokoderm",
"Stonham",
"Streuli",
"Strictly Professional",
"STYLAGE",
"STYLAGE (Vivacy)",
"SUISSELLE",
"Sunekos",
"Sunflower",
"Sunset (Tina Davies x Perma Blend LUXE)",
"Sure Health & Beauty (Oral Syringe range, code DP18390)",
"Sure Thermal",
"SureTemp\u00ae (Welch Allyn / Hillrom)",
"Surshield",
"Sustanon",
"SVR",
"Swan-Morton / Two Face Aesthetics",
"Swann Morton",
"Swann\u2011Morton",
"Swann-Morton",
"Swann-Morton / Qlicksmart",
"SWISSCODE",
"Syneron",
"Syniro",
"Synvisc",
"T\u2011Lab",
"TAD",
"TAD 600",
"TAD Glutathione",
"Talika",
"Tara",
"Tationil",
"TDC",
"TEE-UU",
"TEE-UU MARKER PEN",
"Teleta",
"TEOFIL (Teofil)",
"Teosyal",
"TEOSYAL\u00ae PureSense",
"Teoxane",
"Terumo",
"Tesamorelin",
"Testogel",
"The Crystal Pharmacy IV Vitamin Starter Kit",
"The HADA",
"The Skinny Bottle",
"The Skinny Bottle / Aesthetics Warehouse",
"Thermavein",
"Thomas",
"Time Machine",
"Timesco",
"Timesco EVAC-S",
"Timolol",
"Tina Davies",
"Tina Davies PIXL",
"Tina Davies Professional",
"Tina Davies x Perma Blend Envy Lip Pigments",
"Toffeln",
"Tondaus",
"TONIC X",
"Topilase",
"Topper",
"TOR BAC",
"Tor-Bac",
"Tork",
"TOSKANI",
"TriCare",
"Trimethoprim",
"TRUE FIT",
"Trulicity",
"TSK",
"TSK Laboratory",
"Two Face Aesthetics",
"Two Face Aesthetics ",
"Two Face Aesthetics (TFA)",
"TwoFace Aesthetics",
"Ulthera",
"Ulti Pro",
"Ultimate Circle",
"Ultra Tesla",
"UltraFLEX",
"Ultraformer",
"UltraGrime",
"UltraLow",
"Unbranded",
"Unbranded (OEM digital fridge/freezer thermometer)",
"Unbranded / generic (varies by supplier)",
"Unbranded Bimatoprost Ophthalmic Solution 0.03% (generic; equivalent strength to Lumigan 0.3 mg/ml)",
"Unbranded clinic hand sanitiser (brand not specified on retailer site)",
"Unbranded Research Peptide",
"Underactive Thyroid Test",
"Unifine",
"Unifine SafeControl",
"UNIFIX",
"Uniglove",
"Uniistick",
"Unilite",
"Unisharp",
"Unistik",
"Uniswab",
"Universal",
"Universal Sharps",
"Uniwipe",
"Unknown",
"Unspecified",
"Unspecified (Generic Medical Supply)",
"Uriage",
"UTH",
"VACUETTE",
"Vacutip / generic suction catheter",
"Various (multi-brand package)",
"Veinlite",
"Velancia",
"Velashape",
"Velette",
"Venofix",
"Venosafe",
"Venus",
"Venus Concept",
"Vernacare",
"Vernatry",
"Versatus",
"VICHY",
"Vichy Dermablend",
"Vileda",
"VINEVIDA",
"Vistabel",
"VITAL PROTEINS",
"VIT'ALL+",
"Vitaran",
"Vitrex",
"Vit-X",
"VOLIFIL",
"V-Tech",
"Vygon (Bionector / Octopus 1)",
"Vygon (Octopus with Bionector)",
"Warticon",
"Wegovy",
"Welch Allyn",
"Welch Allyn (a Baxter company)",
"Welch Allyn (Baxter)",
"Welch Allyn (compatible replacement)",
"Welch Allyn (Hillrom / Baxter)",
"Welch Allyn (Hillrom/Baxter)",
"Welch Allyn (vendor part used as replacement on Welch Allyn equipment)",
"Welch Allyn / Braun ThermoScan",
"Welch Allyn / Hillrom",
"Welch Allyn / Mortara",
"Welch Allyn MacroView",
"Welch Allyn ProBP",
"Welch Allyn SureTemp",
"WiQo",
"WiQo PRX-T33",
"WOCK",
"WOMAKE",
"Woopsadaisy",
"Work In Style",
"Work In Style (Code Happy / Cherokee)",
"Work In Style (Key Scrubs Classics)",
"Work In Style / Smart Scrub (retailer-branded product)",
"WOW Bright",
"WOW Fusion",
"Wraplite",
"WRIST'S",
"Xenical",
"XEOMIN",
"Yaqoot",
"Zapain",
"Zensa",
"Zerobase",
"Zeroderm",
"Zerodouble",
"Zidac",
"Zimmer",
"Zivafert",
"Zoff",
]
export const accreditations = 
  [
    "The Aesthetic Awards",
    "Save Face register of accredited practitioners",
    "UberSkin",
    "TCM teaching hospitals",
    "Safety in Beauty Campaign Diamond Awards",
    "Tatler Magazine",
    "Global Health Awards",
    "Global Health & Pharma Magazine Global Excellence Awards",
    "MARBL",
    "Clarins Gold Salon",
    "Care Quality Commission (CQC)",
    "GHP Global Health & Pharma",
    "The Tweakments Guide",
    "Trichology Standards Authority (TSA)",
    "Institute for Apprenticeships and Technical Education (IfATE)",
    "Arun Business Award",
    "Bupa",
    "Spire",
    "Medical Research Council (MRC)",
    "Wiltshire Prestige Awards",
    "British Association of Plastic, Reconstructive and Aesthetic Surgeons (BAPRAS)",
    "University of Oxford",
    "Royal College of General Practitioners",
    "UK Dermatology Clinical Trials Network",
    "EADV - Advanced Paediatric Dermatology",
    "National Beauty Awards (NBA)",
    "BMJ Award",
    "British Society of Paediatric Dermatology",
    "British Association of Dermatologists Wycombe Prize",
    "British Cosmetic Dermatology Group Travelling Fellowship",
    "British Medical Laser Association",
    "British Society of Oculoplastic Surgeons (BOPSS)",
    "University of Birmingham",
    "Innovate Thyroid Eye Disease 2024 symposium",
    "Bupa Platinum Consultant",
    "Clinical and Experimental Dermatology",
    "National Joint Registry",
    "Irish Association of Dermatologists Meeting",
    "British Society of Investigative Dermatology Travel Award",
    "Hereford Times Health & Social Care Awards",
    "Tatler Address Book",
    "Asian Business Chamber of Commerce",
    "Global Excellence Awards",
    "Coventry's Clinic of the Year",
    "Clinical Excellence Award",
    "NHS Halton CCG",
    "Care Quality Commission",
    "Clive Archer Thesis Fellowship",
    "BAD Bristol Cup",
    "GHP Global Excellence Awards",
    "Aesthetic Medicine Awards",
    "Greener Primary Care Wales Scheme",
    "Safety in Beauty Diamond Awards",
    "Cosmetic Surgery & Health Magazine",
    "AO(UK) Award",
    "Barron Prize",
    "British Association of Plastic, Reconstructive and Aesthetic Surgeons (BAPRAS)",
    "BAAPS Travelling Fellowship",
    "Cosmetic Therapist of the Year",
    "London & South East Prestige Awards",
    "London Aesthetic Academy",
    "Imperial College London",
    "DMK Rising Star Award",
    "Leicester University Medical School",
    "James Overton Prize in Dermatology",
    "E2 Media Awards",
    "Royal College of Physicians",
    "British Society for Dermatological Surgery",
    "Ethnic Minority Welsh Women’s Achiever (EMWWA) Award",
    "Aneurin Bevan University Health Board",
    "Everett C. Fox MD Award",
    "American Academy of Dermatology",
    "Tatler Beauty & Surgery Guide",
    "British Medical Association scholarship",
    "Cosmopolitan UK",
    "The Sun",
    "Luxe Magazine",
    "Tatler Cosmetic Surgery Guide",
    "Spear's 500 Adviser list",
    "Scotland Aestheticians",
    "Royal College of General Practitioners (FRCGP)",
    "Royal College of Physicians (UK)",
    "GetHarley Award",
    "Aesthetics Awards",
    "BCAM",
    "Safety in Beauty Awards",
    "Glowday",
    "Circa Skin / Elevate2Expert",
    "Derma Medical",
    "UK HBA Highly Recommended Salon awards",
    "Good Beauty Guide",
    "MelanomaMobil",
    "Trustpilot",
    "Save Face",
    "WhatClinic Patient Service Award",
    "Good Surgeon Guide",
    "4T Medical",
    "Queen Mary University of London SEED Award",
    "Alternative Doctor’s Award",
    "MyFaceMyBody Awards",
    "Forbes",
    "North East Beauty Industry Awards",
    "CosmeDocs",
    "Injector of the Year",
    "International Academy Of Advanced Facial Aesthetics (IAAFA) Lip Sculpting Award",
    "WhatClinic Excellent Customer Service Awards",
    "International Microblading Artist",
    "Global Aesthetic and Laser Conferences",
    "ASME",
    "SAPC",
    "CARER scheme",
    "IMCAS Asia Bangkok",
    "Harley Street Skin Clinic",
    "Irish Association of Dermatologists Travel Bursary",
    "UKDVTN feasibility study grand award",
    "iWantGreatCare Certificate of Excellence",
    "Allergan Medical Faculty",
    "Galderma",
    "Sinclair Pharma",
    "4T Medical",
    "HD Brows",
    "EyebrowQueen",
    "K Govind Medical Aesthetics",
    "Hebden Bridge Group Practice",
    "Care Quality Commission (CQC)",
    "NHS Lanarkshire",
    "Cadzow Health Centre",
    "National Institute for Health Research (NIHR) Academic Clinical Fellowship",
    "Newland Pedley Scholarship",
    "Royal College of Pathology/British Pathology Society Award",
    "BAOMS Travel Award",
    "Ethicon Foundation Award",
    "Lincoln Medical Society Award",
    "Officer of the Order of the British Empire (OBE)",
    "NY Skin Clinic",
    "Safety in Beauty Awards",
    "BTL Exilis Elite Best Face Treatment Award",
    "BTL Aesthetics Blue Star Awards",
    "Redcar & Cleveland Borough Council",
    "BASO oncoplastic travelling scholarship",
    "Royal College of Surgeons of England",
    "BAAPS",
    "Buckinghamshire Healthcare NHS Trust",
    "British Society for Dermatological Surgery ‘Wooden Curette’ award",
    "Skin A&E",
    "Channel 5",
    "Doctify",
    "American Academy of Dermatology (AAD) resident grant",
    "Pharcos Impact Factor Award",
    "Bupa Platinum consultant",
    "NHS Clinical Excellence Awards",
    "Lux Life Health, Beauty & Wellness Awards",
    "Bupa Platinum Consultant Dermatologist",
    "Bupa consultant Finder",
    "BADBIR/BSTOP",
    "National B.A.M.E. Health & Care Awards (GEMS)",
    "PLASTA",
    "PMFA Journal",
    "CELTIC Plastic Surgeons’ Meeting",
    "BAPRAS/ABS collaborative events",
    "Tatler",
    "CoolSculpting Clinic of the Year",
    "Aesthetics Awards",
    "Safety in Beauty Diamond Awards",
    "Sir Archibald Gray Medal",
    "Society of Cosmetic Scientists Medal",
    "American Skin Association Lifetime Achievement Award",
    "European Dermatology Forum (Pro Meritis)",
    "Ulster Tatler Awards",
    "Skincare Clinic of the Year",
    "SKY Clinic",
    "Tatler Cosmetic Guide",
    "My Face My Body Special Contribution Award",
    "The TIMES Best Aesthetic Practitioners",
    "Top Doctors Awards",
    "Royal Society of Medicine",
    "Verified BUPA Platinum Consultant status",
    "AXA PPP",
    "Cigna",
    "WPA",
    "Simply Health",
    "Pru Health / Vitality",
    "The Skin Games",
    "Scottish Makeup Awards",
    "UK Micropigmentation Awards",
    "BBC One The Apprentice",
    "County Durham Business Awards",
    "Robin Harland Prize for Excellence in Teaching",
    "Queen’s University Belfast",
    "The Crown Aesthetics Award",
    "Enterprise Vision Awards (EVAs)",
    "Enhance Clinispa",
    "Perfect Skin Solutions",
    "FACE Conference",
    "UK Hair + Beauty Awards",
    "Wrexham Community Award",
    "Gevro & Jalupro Congress",
    "Aesthetic Medicine Journal",
    "IAAFA Aesthetic Awards"



]


export const distributors = ["Aestheticsrxpharma",
"Aestheticswarehouse",
"Aesthipharma",
"Agelessfillers",
"DDgroup",
"Dermafillerltd",
"Fillersdirect",
"France-health",
"Laserandaesthetics",
"Lpgclinicswholesale",
"Medisave",
"Mirrorpharma",
"Multiple distributors",
"Teleta",
"Thecrystalpharmacy",
"Twofaceaesthetics",
"Wms",
]
export const product_categories = ["Aesthetic Injectables",
"Apparel",
"Blood",
"Clinic Furniture",
"Consumables",
"Education and Training",
"First Aid and PPE",
"Medical and Aesthetic Equipment",
"Nutrition",
"Personal Care and Beauty",
"Pharmaceuticals",
"Therapy",
]
export const modalities: string[] = ['Acne', 'Alopecia', 'Anti Wrinkle Treatment', 'Aqualyx', 'Aviclear', 'B12 Injection', 'Birthmarks', 'Botox', 'Breast Augmentation', 'Cheek Enhancement', 'Chemical Peel', 'Chin Enhancement', 'Aesthetic Skin Consultation', 'Contact Dermatitis', 'CoolSculpting', 'Cysts Treatment', 'Dermapen Treatment', 'Dermatitis Treatment', 'Dermatology Treatments', 'Eczema Treatment', 'Eyebrows and Lashes', 'Facial Treatments', 'Hair Treatments', 'HIFU', 'Hives Treatment', 'Hyperhidrosis', 'Inflammatory Skin Conditions', 'IPL Treatment', 'Keloid Removal', 'Tattoo Removal', 'Laser Treatments', 'Fillers', 'Liposuction', 'Lips', 'Lymphatic Drainage', 'Marionettes', 'Massage', 'Melanoma Treatment', 'Melasma Treatment', 'Micro-needling', 'Microblading', 'Microneedling with Radiofrequency', 'Moles', 'Nails', 'Obagi', 'Patch Testing', 'Photodynamic Therapy (pdt)', 'Pigmentation Treatment', 'Polynucleotide Treatment', 'Profhilo', 'Platelet Rich Plasma', 'Psoriasis', 'Rash Treatment', 'Rosacea Treatment', 'Scarring', 'Seborrheic Keratosis Treatment', 'Seborrhoeic Dermatitis', 'Rhinoplasty', 'Skin Texture and Tightening', 'Skin Booster', 'Skin Cancer', 'Skin Lesions', 'Skin Tags', 'Tear Trough Treatment', 'Threading', 'Varicose Vein Procedure', 'Verruca Treatment', 'Vitamin Therapy', 'Vulval Dermatology', 'Weight Loss']
export const TreatmentMap: Record<string, string> = {
  "Acne": "/directory/treatments/acne.webp",
  "Alopecia": "/directory/treatments/alopecia.webp",
  "Anti Wrinkle Treatment": "/directory/treatments/anti wrinkle treatment.webp",
  "Aqualyx": "/directory/treatments/aqualyx.webp",
  "Aviclear": "/directory/treatments/aviclear.webp",
  "B12 Injection": "/directory/treatments/b12.webp",
  "Birthmarks": "/directory/treatments/birthmarks.webp",
  "Botox": "/directory/treatments/botox.webp",
  "Breast Augmentation": "/directory/treatments/breast-augmentation.webp",
  "Cheek Enhancement": "/directory/treatments/cheek-enhancement.webp",
  "Chemical Peel": "/directory/treatments/chemical-peel.webp",
  "Chin Enhancement": "/directory/treatments/chin-enhancement.webp",
  "Aesthetic Skin Consultation": "/directory/treatments/consultation.webp",
  "Contact Dermatitis": "/directory/treatments/contact-dermatitis.webp",
  "CoolSculpting": "/directory/treatments/coolsculpting.webp",
  "Cysts Treatment": "/directory/treatments/cyst-treatment.webp",
  "Dermapen Treatment": "/directory/treatments/dermapen.webp",
  "Dermatitis Treatment": "/directory/treatments/dermatitis-treatment.webp",
  "Dermatology Treatments": "/directory/treatments/dermatology-treatments.webp",
  "Eczema Treatment": "/directory/treatments/exzema-treatment.webp",
  "Eyebrows and Lashes": "/directory/treatments/eyebrow-lashes.webp",
  "Facial Treatments": "/directory/treatments/facial-treatments.webp",
  "Hair Treatments": "/directory/treatments/hair.webp",
  "HIFU": "/directory/treatments/hifu.webp",
  "Hives Treatment": "/directory/treatments/hives.webp",
  "Hyperhidrosis": "/directory/treatments/Hyperhidrosis.webp",
  "Inflammatory Skin Conditions": "/directory/treatments/inflammatory skin conditions.webp",
  "Ipl Treatment": "/directory/treatments/ipl-treatments.webp",
  "Keloid Removal": "/directory/treatments/keloid removal.webp",
  "Tattoo Removal": "/directory/treatments/laser-tattoo-removal.webp",
  "Laser Treatments": "/directory/treatments/laser-treatments.webp",
  "Fillers": "/directory/treatments/lip-filler-6485474_640.webp",
  "Liposuction": "/directory/treatments/liposuction illustration.webp",
  "Lips": "/directory/treatments/lips.webp",
  "Lymphatic Drainage": "/directory/treatments/lymphatic-drainage.webp",
  "Marionettes": "/directory/treatments/marionettes.webp",
  "Massage": "/directory/treatments/massage.webp",
  "Melanoma Treatment": "/directory/treatments/melanoma-treatments.webp",
  "Melasma Treatment": "/directory/treatments/melasma.webp",
  "Micro-needling": "/directory/treatments/micro-needling.webp",
  "Microblading": "/directory/treatments/microblading.webp",
  "Microneedling With Radiofrequency": "/directory/treatments/microneedling with radiofrequency.webp",
  "Moles": "/directory/treatments/moles.webp",
  "Nails": "/directory/treatments/nail-polish-2112358_640.webp",
  "Obagi": "/directory/treatments/obagi.webp",
  "Patch Testing": "/directory/treatments/patch-testing.webp",
  "Photodynamic Therapy (pdt)": "/directory/treatments/photodynamic therapy.webp",
  "Pigmentation Treatment": "/directory/treatments/pigmentation-treatments.webp",
  "Polynucleotide Treatment": "/directory/treatments/polynucleotide-treatment.webp",
  "Profhilo": "/directory/treatments/profhilo.webp",
  "Platelet Rich Plasma": "/directory/treatments/prp.webp",
  "Psoriasis": "/directory/treatments/psoriasis.webp",
  "Rash Treatment": "/directory/treatments/rash-treatment.webp",
  "Rosacea Treatment": "/directory/treatments/rosacea.webp",
  "Scarring": "/directory/treatments/scarring.webp",
  "Seborrheic Keratosis Treatment": "/directory/treatments/seborrheic keratosis.webp",
  "Seborrhoeic Dermatitis": "/directory/treatments/seborrhoeic dermatitis.webp",
  "Rhinoplasty": "/directory/treatments/side-view-doctor-checking-patient-before-rhinoplasty.webp",
  "Skin Texture and Tightening": "/directory/treatments/skin texture and tightening.webp",
  "Skin Booster": "/directory/treatments/skin-booster.webp",
  "Skin Cancer": "/directory/treatments/skin-cancer.webp",
  "Skin Lesions": "/directory/treatments/skin-lesions.webp",
  "Skin Tags": "/directory/treatments/skin-tags.webp",
  "Tear Trough Treatment": "/directory/treatments/tear-through-treatments.webp",
  "Threading": "/directory/treatments/threading.webp",
  "Varicose Vein Procedure": "/directory/treatments/varicose-vein.webp",
  "Verruca Treatment": "/directory/treatments/verruca treatment.webp",
  "Vitamin Therapy": "/directory/treatments/vitamin-therapy.webp",
  "Vulval Dermatology": "/directory/treatments/vulval-dermatology.webp",
  "Weight Loss": "/directory/treatments/weight-loss.webp"
};
export const edu = [
    "BA",
    "BAO",
    "BA(Hons)",
    "B.A.",
    "BA Cantab",
    "BA Oxon",
    "BMLA",
    "BM",
    "BM BCh",
    "BM BChir",
    "BMBS",
    "BMBS(Hons)",
    "BMedSci",
    "BMedSc",
    "BMedsci",
    "BN",
    "BN(Hons)",
    "B.Nurs",
    "BPharm",
    "BSc",
    "BSc(Hons)",
    "BSc PodM",
    "BSc Nursing",
    "BDS",
    "BDS(Hons)",
    "Cert Aes Med",
    "CIDESCO",
    "CCT",
    "DFSRH",
    "DFMS",
    "DCH",
    "DipDerm",
    "DipMSKMed",
    "DipNut",
    "Dip Obs",
    "DM",
    "DRCOG",
    "DTM&H",
    "EBHS",
    "EDIC",
    "FFD RCSI",
    "FMCS",
    "FRCA",
    "FRCP",
    "FRCS","Medical Degree",
    "FRCGP",
    "GPhC",
    "ITEC",
    "MA",
    "MA Cantab",
    "MB",
    "MB BCh BAO",
    "MB BS",
    "MBChB",
    "MBChB(Hons)",
    "MBBS",
    "MB BChir",
    "MB ChB",
    "MBChB Oxon",
    "MBChB Cantab",
    "MClinDent",
    "MClinDent Pros",
    "MD",
    "MFDS",
    "MFDS RCS",
    "MJDF",
    "MPhil",
    "MRCGP",
    "MRCOG",
    "MRCP",
    "MRCP(Derm)",
    "MRCS",
    "MRD Pros",
    "MSc",
    "MSc Med Ed",
    "MSc Nursing",
    "PGCE",
    "PGCert",
    "PGCert Clin Ed",
    "PGCert Med Ed",
    "PGCME",
    "PGDip",
    "PGDip Derm",
    "PGDip MH",
    "PGDip Cosmetic Medicine",
    "PhD",
    "QIF","Consultant Dermatologist",
    "V300","Level 7","Level 6","Level 5","VTCT",
    " BHons Nursing", "Surgeon", "Accredited Trainer","Therapist","Trichologist", "Level 7","INP", "BSC Hons", "GMC", "Registered Medical Practitioner", "Aesthetic Practitioner"]

export const spec = ["Trichologist","Stylist","Technician","Manager","Admin","Hairdresser","Associate","Therapist","Practitioner","Owner","Coordinator","Pharmacist","Founder","Director","Nurse","Consultant","Specialist"
]
export const locations: string[] = [
  "Alderley",
"Wembley",
"Salford",
"Redcar",
"Glasgow",
"Livingston",
"London",
"Abertillery",
"Grimsby",
"Warrington",
"Belfast",
"Ballymena",
"Swansea",
"Kingston",
"Pontyclun",
"Merthyr",
"Southport",
"Telford",
"St.",
"Denny",
"Wilmslow",
"Cookstown",
"Derby",
"Stockton-on-Tees",
"Cwmbran",
"Hornchurch",
"Caernarfon",
"Farnham",
"Reading",
"Knutsford",
"Surbiton",
"Manchester",
"Dalry",
"Windsor",
"Gloucester",
"Bridgend",
"Colne",
"Tunbridge",
"Leeds",
"Sheffield",
"Eastbourne",
"Bedford",
"Crumlin",
"Bristol",
"Hounslow",
"Plymouth",
"York",
"Ebbw",
"Airdrie",
"Liverpool",
"Stockport",
"Leicester",
"Cardiff",
"Thornton-Cleveleys",
"Ayr",
"Bonnyrigg",
"Bromley",
"South",
"Tetbury",
"Cleckheaton",
"Brighton",
"Bracknell",
"Harrogate",
"Lancaster",
"Warlingham",
"Newry",
"Doncaster",
"Solihull",
"Uckfield",
"Oakham",
"Coulsdon",
"Paisley",
"Weston-super-Mare",
"Rochester",
"Knottingley",
"Great",
"Bradford",
"Crowborough",
"Durham",
"Beckenham",
"Oldham",
"Huntingdon",
"Birmingham",
"Motherwell",
"Dundee",
"Wingate",
"Bexhill-on-Sea",
"Cramlington",
"Barnet",
"Colwyn",
"Middlesbrough",
"Cheltenham",
"Edinburgh",
"Newcastle",
"Portsmouth",
"Llangefni",
"Crewe",
"Preston",
"Coventry",
"Irvine",
"Hove",
"Newmilns",
"Croydon",
"Truro",
"Shotts",
"Pontefract",
"Southampton",
"Stourbridge",
"Teddington",
"West",
"Cumnock",
"Royal",
"Bolton",
"Craigavon",
"Peterborough",
"Dartford",
"Abergavenny",
"Londonderry",
"Clackmannan",
"Isle",
"Portstewart",
"Blackwood",
"Chatham",
"Stafford",
"Milton",
"Magherafelt",
"Barking",
"Sutton",
"Rochdale",
"Oxford",
"Llanelli",
"Dunstable",
"Falkirk",
"Rotherham",
"Y",
"Altrincham",
"Newport",
"Saltcoats",
"Leigh",
"Wigan",
"Kilmacolm",
"Bishop",
"East",
"Nottingham",
"Newtownabbey",
"Cambridge",
"Hamilton",
"Hartlepool",
"Lostwithiel",
"Wakefield",
"Gourock",
"Middlewich",
"Conwy",
"Barry",
"Scunthorpe",
"Brentford",
"Swindon",
"Beverley",
"Gillingham",
"Horley",
"Normanton",
"Antrim",
"Aberdeen",
"Penarth",
"Luton",
"Wallington",
"Haverfordwest",
"Dumfries",
"Newtownards",
"Leamington",
"Stirling",
"Shefford",
"Bebington",
"Biggar",
"Saint",
"Banstead",
"Castlederg",
"Newquay",
"Llandudno",
"Clydebank",
"Driffield",
"Bath",
"Stanley",
"Eastleigh",
"Bathgate",
"Darlington",
"Stanmore",
"Kilmarnock",
"Gerrards",
"Bournemouth",
"Sidcup",
"Pontypridd",
"Rhyl",
"Dalkeith",
"Huddersfield",
"Chester",
"Barnsley",
"Crowthorne",
"Brentwood",
"Fareham",
"Wrexham",
"Southend-on-Sea",
"Basildon",
"Enniskillen",
"Walsall",
"Strabane",
"Lanark",
"Prescot",
"Borehamwood",
"Berkhamsted",
"Romford",
"Broxburn",
"Monmouth",
"Enfield",
"Winchester",
"Hengoed",
"Rugby",
"North",
"Liversedge",
"Aughnacloy",
"Aberystwyth",
"Saltburn-by-the-Sea",
"Bargoed",
"Colchester",
"Kettering",
"Leighton",
"Christchurch",
"Hastings",
"Inverness",
"Arundel",
"Sunderland",
"Canterbury",
"Nantwich",
"Edgware",
"Larne",
"Stornoway",
"Dunoon",
"Haddington",
"Wokingham",
"Stoke-on-Trent",
"Isleworth",
"Keighley",
"Dunfermline",
"Worthing",
"Warwick",
"Hampton",
"Farnborough",
"Northwood",
"Blackburn",
"Cheadle",
"Swadlincote",
"Bellshill",
"Perth",
"Bury",
"Banbridge",
"Wirral",
"Carmarthen",
"Dudley",
"Hawick",
"Armagh",
"Cowbridge",
"Llanfairpwllgwyngyll",
"Hebden",
"Kinross",
"Twickenham",
"High",
"Holyhead",
"Gateshead",
"Runcorn",
"Pudsey",
"Trimdon",
"Ashford",
"Westcliff-on-Sea",
"Buckie",
"Batley",
"Chislehurst",
"Ilford",
"Knaresborough",
"Littlehampton",
"Rye",
"Caerphilly",
"Penzance",
"Alloa",
"Houghton",
"Hull",
"Bo'ness",
"Marlow",
"Bangor",
"Northwich",
"Coleraine",
"Chalfont",
"Stretford",
"Banchory",
"Bacup",
"Arbroath",
"Falmouth",
"Hereford",
"Skipton",
"Hitchin",
"Limavady",
"Kirriemuir",
"Stalybridge",
"Ilkley",
"Darwen",
"Borth",
"Skelmorlie",
"Wallsend",
"Grays",
"Richmond",
"Dereham",
"Elgin",
"Deeside",
"Cottingham",
"Peterculter",
"Blackpool",
"Wexham",
"Ballynahinch",
"Ormskirk",
"Woodford",
"Brough",
"Halifax",
"Llangollen",
"Maldon",
"Wolverhampton",
"Newbury",
"Loughborough",
"Hailsham",
"Holywood",
"Norwich",
"Bretton",
"Blairgowrie",
"Llandysul",
"Yeovil",
"Barnoldswick",
"Chester-le-Street",
"Potters",
"Nailsworth",
"Helensburgh",
"Caldicot",
"Carmarthenshire",
"Llanrwst",
"Maidenhead",
"Brigg",
"Malmesbury",
"Omagh",
"Birkenhead",
"Ruislip",
"Heathfield",
"Consett",
"Macclesfield",
"Lincoln",
"Gainsborough",
"Southsea",
"Rossendale",
"Sandbach",
"Dungannon",
"Hillsborough",
"Chesterfield",
"hollow",
"Port",
"Berwick-upon-Tweed",
"Hungerford",
"Kings",
"Hertford",
"Cradley",
"Harrow",
"Chippenham",
"Renfrew",
"Sale",
"Chelmsford",
"Neath",
"Callington",
"Mirfield",
"Ossett",
"Banwell",
"Pinner",
"Fochabers",
"Troon",
"Everlast",
"Seaham",
"Crook",
"Tarporley",
"Lampeter",
"Skegness",
"Barrow-upon-Humber",
"Aberdare",
"Newton-le-Willows",
"Bedale",
"Stamford",
"Poulton-le-Fylde",
"Beaconsfield",
"Shrewsbury",
"Henlow",
"Wednesbury",
"Todmorden",
"Mitcham",
"Pwllheli",
"Tipton",
"Kirkcaldy",
"Oswestry",
"Ballycastle",
"Waterlooville",
"Lisburn",
"Cross",
"Peacehaven",
"Gaerwen",
"Mold",
"Havant",
"Carrickfergus",
"Bridge",
"Cowes",
"Washington",
"New",
"Wishaw",
"Wigston",
"Holmfirth",
"Slough",
"Aylesbury",
"Biggleswade",
"Snodland",
"Linlithgow",
"Bingley",
"Downpatrick",
"Trowbridge",
"Kilrea",
"Horsham",
"Northampton",
"Didcot",
"Newton",
"The",
"Peterlee",
"Gravesend",
"Forfar",
"Worcester",
"Castleford",
"Stockbridge",
"Basingstoke",
"Lossiemouth",
"Otley",
"Leigh-on-Sea",
"Totland",
"Haywards",
"Harlow",
"Bodorgan",
"Widnes",
"Kirkwall",
"Pathhead",
"St",
"Poole",
"Denbigh",
"Coatbridge",
"Pontypool",
"Sowerby",
"Shetland",
"Seaford",
"Carshalton",
"Upminster",
"Yarm",
"Cleethorpes",
"Llandrindod",
"Newmarket",
"Holywell",
"Kenilworth",
"Menai",
"Tonypandy",
"Radstock",
"Congleton",
"Chipping",
"Westerham",
"Uxbridge",
"Ascot",
"Broadstone",
"Newcastle-under-Lyme",
"Lymm",
"Bushey",
"Pentraeth",
"Orkney",
"Topiary",
"Oldbury",
"Wimborne",
"Porth",
"Latchmeads",
"Maulden",
"Dunblane",
"Ross-on-Wye",
"Dorchester",
"Aberfeldy",
"Brierley",
"Ballyclare",
"Darvel",
"Porthmadog",
"Stanford-le-Hope",
"Wells",
"Prestonpans",
"Ashton-under-Lyne",
"Nelson",
"Hatfield",
"Bryngwran",
"Devizes",
"Boston",
"Buckingham",
"Ruthin",
"WN58RR",
"Orpington",
"Burton-on-Trent",
"parking",
"Liskeard",
"Abingdon",
"Spilsby",
"Maghera",
"Brighouse",
"Wallasey",
"Winsford",
"Bexleyheath",
"Welling",
"Strathaven",
"Blaenau",
"Wood",
"Alton",
"Dewsbury",
"Heanor",
"ELY",
"Billericay",
"Wallingford",
"Greenhithe",
"Alderminster",
"Anlaby",
"Sevenoaks",
"Marlborough",
"Lydney",
"Staines",
"Bridgwater",
"Hyde",
"Elland",
"Keston",
"Launceston",
"Robertsbridge",
"Maesteg",
"Axbridge",
"Goole",
"Shipley",
"Prestwick",
"Romsey",
"Musselburgh",
"Broughshane",
"Crawley",
"Battle",
"Bilston",
"Hessle",
"Bexley",
"Melton",
"Melksham",
"Brinkworth",
"Ealing",
"Chepstow",
"Leyland",
"Narberth",
"Aberaeron",
"Accrington",
"Bonnybridge",
"Chigwell",
"Bridgnorth",
"Tranent",
"Selby",
"Stratford-upon-Avon",
"Frodsham",
"Blyth",
"Kilwinning",
"Prestatyn",
"Matlock",
"Treorchy",
"Clevedon",
"Jarrow",
"Ballymoney",
"Forest",
"Hayes",
"Dunbar",
"Corby",
"Lewes",
"Chorley",
"Flint",
"Gullane",
"Kelso",
"Whitley",
"Purfleet",
"Burgess",
"Montrose",
"Bedworth",
"Wotton-under-Edge",
"Hemel",
"Wickford",
"Cardigan",
"Ellesmere",
"Benfleet",
"Alfreton",
"Harpenden",
"Southall",
"Thurrock",
"Newhaven",
"Hassocks",
"Ware",
"Chesham",
"Symington",
"Wemyss",
"Drumquin",
"Halesowen",
"Ulceby",
"Clitheroe",
"EMCRF",
"Boldon",
"Billingham",
"Lauder",
"Pembroke",
"Shanklin",
"Epsom",
"Broughton",
"Witham",
"Alexandria",
"Frampton",
"Porthcawl",
"BOXSTART",
"Lytham",
"Guisborough",
"Tyn-y-Gongl",
"Llannerch-y-medd",
"Dumbarton",
"Larkhall",
"Stroud",
"Alva",
"Bromsgrove",
"Chichester",
"Heywood",
"Helston",
"Henley-on-Thames",
"Whitchurch",
"4QR",
"Aberpwll",
"Keith",
"Dagenham",
"Mauchline",
"Kilgetty",
"Thornton",
"Winscombe",
"Wetherby",
"Tonbridge",
"Smethwick",
"UK",
"Morpeth",
"Tarbert",
"Ryde",
"Rayleigh",
"Littleborough",
"Silsoe",
"Purley",
"Belper",
"Corwen",
"Dukinfield",
"Rhosneigr",
"Ferryhill",
"Cranbrook",
"Buckley",
"Hoylake",
"Girvan",
"Redruth",
"Bishopton",
"Willenhall",
"Stevenage",
"Bedfordshire",
"Cockermouth",
"Moffat",
"Bootle",
"Glenrothes",
"Barton-upon-Humber",
"Clogher",
"Longhope",
"Llanfairfechan",
]