import { create } from "zustand";
import { Clinic, Practitioner, SearchFilters } from "@/lib/types";
import { getClinics, getPractitioners} from "@/lib/cachedData";
import {consolidate, parse_text, parse_addresses, parse_numbers} from "@/lib/utils"

function parseLabels(label: string): [boolean, string] | null {
  try {
    const jsonReady = label
      .trim()
      // normalize Python-style booleans
      .replace(/\bTrue\b/g, "true")
      .replace(/\bFalse\b/g, "false")
      // normalize single quotes to double quotes
  
      // handle empty string edge case: [False, ""] or [False, ]
    

    const parsed = JSON.parse(jsonReady);
    return parsed;
  } catch (err) {
    return null;
  }
}



function safeParse(v: any) {
  try {
    return JSON.parse(v);
  } catch {
    return null;
  }
}

export function transformClinic(raw: any): Clinic {
 
  return {
    slug: raw.slug.toLowerCase()
    .replace(/&|\+/g, 'and')
    .replace(/\s+/g, '-')
    .replace(/[()]/g, ''),
    image: raw.image,
    url: raw.links,
    rating: parseFloat(raw.rating),
    reviewCount: parseInt(raw.review_count),
    category: raw.category,
    gmapsAddress: parse_addresses(raw.gmaps_address),
    //gmapsLink: raw.gmaps_link,
    gmapsPhone: raw.gmaps_phone.replace("Phone: ", "").trim(),
    gmapsReviews: safeParse(raw.gmaps_reviews),
    reviewAnalysis: safeParse(raw["Review Analysis"]),
    weighted_analysis: safeParse(raw["weighted_analysis"]),
    City: raw.City,
    x_twitter: raw.x_twitter,
    facebook: raw.facebook,
    instagram: raw.instagram,
    twitter: raw.twitter,
    youtube: raw.youtube,
    Linkedin: raw.Linkedin,
    website: raw.website,
    email: raw.email,
    isSaveFace: raw.isSaveFace,
    isDoctor: raw.isDoctor,
    isJCCP: parseLabels(raw.isJCCP),
    isCQC: parseLabels(raw.isCQC),
    isHIW: parseLabels(raw.isHIW),
    isHIS: parseLabels(raw.isHIS),
    isRQIA: parseLabels(raw.isRQIA),
    about_section: raw.about_section,
    hours: safeParse(raw.hours),
    Practitioners: safeParse(raw.Practitioners),
    Insurace: safeParse(raw.Insurace),
    Payments: safeParse(raw.Payments), 
    Fees: safeParse(raw.Fees),
  };
}
export function transformPractitioner(raw: any): Practitioner {
 
  return {
    //id: raw["ID"].toString(),
    Name: raw.Name,
    slug: raw.Name.toLowerCase().replace(/\s+/g, "-"),
    image: !raw.Image || raw.Image === "https://www.jccp.org.uk/content/images/no-image.jpg"
  ? parse_text(raw.image)
  : raw.Image,
    profession: parse_text(raw["PROFESSION:"]).trim(),
    // regulatoryBody: raw["REGULATORY BODY:"],
    // registrationPin: raw["REGISTRATION PIN NUMBER:"],
    qualification: raw["QUALIFICATION: (To Date)"].trim(),
     modality: consolidate(raw["SPECIALTIES"]),
    // memberSince: raw["MEMBER SINCE:"],
    // otherMemberships: raw["OTHER MEMBERSHIPS:"],
    // restrictions: raw["RESTRICTIONS:"],
     url: raw.url,
     rating: parse_numbers(raw.rating),
     reviewCount: parse_numbers(raw.review_count),
     category: raw.category,
     gmapsAddress: parse_addresses(raw.gmaps_address),
     //gmapsLink: raw.gmaps_link,
    // gmapsPhone: raw.gmaps_phone.replace("Phone: ", "").trim(),
    gmapsReviews: JSON.parse(raw.gmaps_reviews),
    reviewAnalysis: safeParse(raw["Review Analysis"]),
  };
}
// -----------------------------
// Types
// -----------------------------
interface SearchState {
  filters: SearchFilters
  setFilters: (filters: SearchFilters) => void
}

export const useSearchStore = create<SearchState>((set) => ({
  filters: {
    type: "Clinic",
    query: "",
    category: "",
    location: "",
    rating: 0,
    services: [],
  },
  setFilters: (filters) => set({ filters }),
}))

interface DataStore {
  clinics: Clinic[];
  practitioners: Practitioner[];
  categories: string[];
  modalities: string[];
  professions: string[];
  locations: string[];
  loading: boolean;
  error?: string;
  initialized: boolean;
  fetchData: () => Promise<void>;
}

export const useDataStore = create<DataStore>((set, get) => ({
  clinics: [],
  practitioners: [],
  categories: [],
  modalities: [],
  professions: [],
  locations: [],
  loading: false,
  error: undefined,
  initialized: false,

  fetchData: async () => {
    const state = get();
    
    // Check if already initialized in this session
    if (state.initialized) {
      console.log("✅ DataStore: Already initialized");
      return;
    }

    if (state.loading) {
      console.log("⏳ DataStore: Already fetching...");
      return;
    }

    console.log("🔄 DataStore: Fetching data...");
    set({ loading: true, error: undefined });

    try {

      
      const clinics = await getClinics();
      const practitioners = await getPractitioners();
      const clinicsData = clinics.map(transformClinic);
      const practitionersData = practitioners.map(transformPractitioner);

    


      // ---- Derive unique sets ----
      const categories: string[] = [
        "Beautician",
        "Beauty Parlour",
        "Children's hospital",
        "Community health center",
        "Consultant",
        "Cosmetic dentist",
        "Cosmetic surgeon",
        "Cosmetics industry",
        "Dental clinic",
        "Dentist",
        "Dermatologist",
        "Diagnostic center",
        "Doctor",
        "Esthetics service",
        "Eye care center",
        "Family practice physician",
        "General hospital",
        "General practitioner",
        "Government hospital",
        "Hair removal service",
        "Hair replacement service",
        "Hair salon",
        "Hair transplantation clinic",
        "Hairdresser",
        "Health and beauty shop",
        "Health consultant",
        "Home health care service",
        "Hospital",
        "Hospital department",
        "Housing complex",
        "Laser hair removal service",
        "Lasik surgeon",
        "Medical Center",
        "Medical clinic",
        "Medical group",
        "Medical office",
        "Medical spa",
        "Nurse practitioner",
        "Nursing home",
        "Office space rental agency",
        "Orthopedic clinic",
        "Osteopath",
        "Permanent make-up clinic",
        "Plastic surgeon",
        "Plastic surgery clinic",
        "Private hospital",
        "Registered general nurse",
        "Skin care clinic",
        "Specialized clinic",
        "Surgeon",
        "Travel clinic",
        "University hospital",
        "Walk-in clinic",
        "Wellness center",
        "Women's health clinic"
      ]
      
      

      let modalities: string[] = ["Injectables",
"Botox / Anti-wrinkle Injections",
"wrinkle Relaxing Injections (Botulinum Toxin)",
"Anti-ageing Injectables",
"Dermal Fillers",
"Lip Filler",
"Cheek Augmentation",
"Jawline Sculpting",
"Chin Enhancement",
"Tear Trough Filler / Under-eye Rejuvenation",
"Non-surgical Rhinoplasty (Liquid Rhinoplasty)",
"Facial Harmonisation",
"Full-face Aesthetic Rejuvenation",
"8-point Facelift (Non-surgical)  ",
"Lip Augmentation",
"Lip Enhancement",
"Lip Beautification",
"Dermal Fillers (Lips, Cheeks, Chin, Jawline)",
"Facial Volume Restoration",
"Skin Boosters",
"Profhilo",
"Profhilo Skin Boosters  ",
"Skin Boosters & Polynucleotides",
"Polynucleotide Injections",
"Polynucleotide Skin Rejuvenation",
"Sunekos / Jalupro / Nucleofill",
"Sculptra",
"Radiesse",
"PDO Threads / Thread Lifts",
"Silhouette Soft Thread Lift",
"APTOS Thread Lifts",
"PDO Thread Lifts",
"Non-surgical Facelift",
"Non-surgical Facial Rejuvenation",
"Facial Rejuvenation",
"Liquid Facelift",
"Facial Contouring",
"Facial Volumisation",
"Microdosing Aesthetic Injectables",
"Natural Upper-face Anti-wrinkle and Filler Work",
"Jawline & Chin Contouring",
"Lip Cage & Tear-Trough Dermal Filler Treatments",
"Advanced Facial Aesthetics",
"Bespoke Aesthetic Enhancements",
"Natural-looking Facial Harmonisation",
"Facial Asymmetry Correction",
"Muscle Relaxation Treatment (for Wrinkles)",
"Bruxism Treatment (using Botox)",
"Gummy Smile Correction",
"Masseter Reduction (Jawline Slimming)",
"Hyperhidrosis Treatment (Botox)",
"Migraine Treatment (using Botox)",
"Joint Pain Injections (Osteoarthritis)",
"TMJ Dysfunction Treatment",
"Injectable Aesthetic Treatments",
"Facial Anatomy & Aesthetics",
"Ultrasound-guided Filler Placement",
"Complication Management in Cosmetic Medicine",
"Aesthetic Injectables Training & Education",
"Skin Treatments",
"Skin Rejuvenation",
"Medical Grade Facials",
"Luxury Facials",
"Hydrafacial",
"Hydrafacial and Medical-grade Skin Rejuvenation  ",
"Medical Skincare Facials",
"Skin Rejuvenation Facials",
"Advanced Facials",
"Skin Health Programmes",
"Bespoke Skin Health Programmes",
"Medical Aesthetic Rejuvenation",
"Skin Quality & Anti-ageing",
"Skin Hydration & Rejuvenation",
"Skin Therapy",
"Skin Peels",
"Chemical Peels",
"Medical-Grade Chemical Peels",
"AlumierMD Chemical Peels",
"Professional Chemical Peels",
"Medical-Grade Peels",
"Doctor-Grade Chemical Skin Peels",
"Obagi Medical Skincare Protocols  ",
"Chemical Peel",
"Superficial, Medium, and Deep Peels",
"Perfect Peel",
"Exfoliation & Chemical Exfoliation",
"Skin Resurfacing",
"Laser Skin Resurfacing",
"CO2 Laser Resurfacing",
"Fractional CO2 Laser",
"Fully Ablative Laser Skin Resurfacing",
"Fraxel Laser Resurfacing  ",
"Aviclear Laser Acne Treatment",
"Ultraclear / Halo / Profractional",
"Skin Resurfacing Treatments",
"Laser Skin Therapy",
"Laser Skin Rejuvenation",
"Laser Dermatology",
"Laser & Energy-based Skin Rejuvenation",
"Laser & Device-based Skin Rejuvenation",
"Laser & Light-based Skin Rejuvenation",
"Photo Rejuvenation Treatment",
"Neogen Plasma Skin Resurfacing",
"Tixel Skin Rejuvenation",
"SCAAR Fx",
"Skin Tightening",
"Radiofrequency Skin Tightening",
"HIFU (High-Intensity Focused Ultrasound)  ",
"Ultherapy",
"Ultraformer",
"Morpheus8",
"Morpheus8 Microneedling & RF  ",
"Sylfirm X",
"Sofwave",
"face/Neck Tite",
"Endolift Non-surgical face/Neck Lift",
"Microfocused Ultrasound with Visualization",
"Ultrasound-based Non-surgical Lifting",
"Plasma-pen (Fibroblast) Skin Lifting",
"Skin Laxity Treatment",
"Skin Texture Improvement",
"Skin Tone & Texture Correction",
"Skin Barrier Repair",
"Skin Revitalisation",
"Skin Health Optimisation",
"Skin Wellness Treatments",
"AI Skin Analysis & Bespoke Plans",
"Visia Skin Analysis",
"Digital Mole Scanning",
"Skin Analysis & Prescription Skincare",
"Medical Skincare & Home-care Advice",
"Medical-Grade Skincare",
"ZO Skin Health",
"Obagi Skincare Programs",
"Pca Skincare",
"Personalised Prescription-strength Skincare",
"Skin Health & Longevity-led Aesthetics",
"Microneedling",
"Skinpen Microneedling",
"Dermapen 4  ",
"Medical Microneedling",
"Collagen Induction Therapy",
"Derma-rolling & Microneedling",
"Skin Needling",
"Microneedling with PRP",
"PRP (Platelet-Rich Plasma) for Skin  ",
"Exosome Therapy",
"PRF (Platelet-Rich Fibrin) Therapy  ",
"Mesotherapy",
"Medical Microneedling / Exosome Therapy",
"PRP & Microneedling",
"PRP for Skin & Hair",
"PRP Facial",
"Laser Treatments",
"IPL (Intense Pulsed Light)",
"Lumecca IPL",
"BBL Heroic / BBL / Clearsilk",
"led Light Therapy",
"Dermalux led Therapy",
"led Phototherapy",
"Aerolase",
"Nd:YAG Laser",
"Fractional Lasers",
"Co2RE Intima",
"Laser Therapy for Skin Rejuvenation",
"Laser & IPL Skin Resurfacing",
"Laser & IPL Hair Removal",
"Laser Hair Removal",
"Laser Hair & Skin Treatments",
"Laser Tattoo Removal",
"Laser for Pigmentation",
"Laser for Acne & Rosacea",
"Laser for Scarring",
"Laser for Birthmarks",
"Laser for Vascular Lesions",
"Laser & Plasma Skin Rejuvenation",
"Laser Scar Treatment",
"Laser Skin Tightening",
"Laser Doppler Imaging (for Burn Assessment)",
"Laser Surgery (Cosmetic & Reconstructive)  ",
"Laser for Wart & Skin Tag Removal",
"Laser for Mole & Lesion Removal",
"Laser for Skin Cancer",
"Photodynamic Therapy (PDT)",
"Photorejuvenation",
"Fat-dissolving Injections",
"Aqualyx",
"Aqualyx Fat-dissolving Injections  ",
"A-qualyx Non-surgical Fat Reduction",
"Injection Lipolysis",
"CoolSculpting",
"3D Lipo  ",
"Bodytite / Bodytite",
"Armtite / Thigh Laxity Treatments  ",
"Vaser Liposuction",
"Vaser Liposculpture",
"Vaser Liposuction & Advanced Body-Contouring",
"Body Sculpting",
"Body Contouring",
"High-definition Liposuction",
"Brazilian Butt Lift (BBL)",
"Fat-freezing & Body-Contouring",
"Emsculpt Neo",
"Non-surgical Fat Reduction",
"Non-surgical Body Contouring",
"Body Sculpting & Toning",
"Fat dissolving Injections (Aqualyx™)",
"Fat Reduction in Sub-mental & Jowl Areas",
"Body Reshaping",
"Abdominoplasty (Tummy Tuck)",
"Mummy Makeover",
"Thigh Lift / Arm Lift / Brachioplasty",
"Body Lift",
"360-Body Lift",
"Hair Loss Treatments",
"Hair Regrowth Treatments",
"PRP for Hair Loss",
"Mesotherapy for Hair Loss",
"DPCP Immunotherapy",
"FUE Hair Transplant Surgery",
"FUE/DHI Hair Transplants",
"DHI Hair Transplantation",
"Hair Transplant Surgery",
"Scalp Micropigmentation",
"Hair Restoration",
"Hair & Scalp Disorders",
"Alopecia (Male/Female Pattern, Alopecia Areata, Trichotillomania)  ",
"Androgenetic Alopecia",
"Telogen Effluvium",
"Seborrheic Dermatitis / Scalp Psoriasis",
"Hair Breakage & Oily Scalps",
"Afro-textured Hair Loss (CCCA, Traction Alopecia, FFA)",
"Scarring Alopecia",
"Trichoscopy (Hair & Scalp Analysis)  ",
"Hair Growth Treatments",
"Platelet-Rich Plasma (PRP) Therapy",
"PRP/PRF Therapy",
"Hair Loss Diagnosis & Treatment",
"Hairline",
]
      const professions = ["Consultant Dermatologist",
"General Practitioner (GP)",
"Aesthetic Physician",
"Aesthetic Doctor",
"Cosmetic Doctor",
"Medical Aesthetic Practitioner",
"Consultant Plastic & Reconstructive Surgeon",
"Consultant Plastic Surgeon",
"Consultant Cosmetic Surgeon",
"Consultant Aesthetic Physician",
"Consultant Dermatologist & Aesthetic Physician",
"Consultant Dermatologist & Mohs Surgeon",
"Consultant Dermatologist & Skin Surgeon",
"Consultant Dermatologist & Medical Director",
"Consultant Dermatologist & Clinical Director",
"Consultant Dermatologist & Founder",
"Consultant Dermatologist & Pigmentation Specialist",
"Consultant Dermatologist & Hair/Scalp Specialist",
"Consultant Dermatologist & Skin-of-Colour Specialist",
"Consultant Dermatologist – Paediatric & Adult",
"Consultant Dermatologist – Adult & Paediatric",
"Consultant Anaesthetist & Aesthetic Doctor",
"Consultant Anaesthetist",
"Consultant Vascular Surgeon",
"Consultant Vascular & Endovascular Surgeon",
"Consultant Oculoplastic Surgeon",
"Consultant Ophthalmologist & Oculoplastic Surgeon",
"Consultant Oncoplastic Breast Surgeon",
"Consultant Maxillofacial Surgeon",
"Consultant Gender-Affirming Surgeon",
"Consultant Facial Plastic & Hair Restoration Surgeon",
"Consultant Cosmetic & Preventative Medicine Physician",
"Consultant Cosmetic Dermatologist",
"Consultant Integrative Skin & Hormone Doctor",
"Consultant in Internal Medicine",
"Consultant Physician",
"Consultant Gynaecologist & Medical Director",
"Consultant in Reproductive Medicine & Gynaecology",
"Specialist GP Dermatology",
"GP with Specialist Interest in Dermatology (GPwSI/GPwER)",
"GP with Extended Role in Dermatology & Minor Surgery",
"GP & Aesthetic Medicine Specialist",
"GP & Minor Skin Surgeon",
"GP & Dermatology Consultant",
"GP Partner",
"Salaried GP",
"Locum GP",
"Senior Partner (GP Practice)",
"Lead GP",
"GP Principal",
"GP Trainer",
"GP Registrar",
"GP with Special Interest in Mental Health & Cosmetic Dermatology",
"GP & Lifestyle Medicine Physician",
"GP | Dermatology & Aesthetic Medicine Specialist",
"GP & Women’s Health Specialist",
"GP & Aesthetic Physician",
"Aesthetic Practitioner",
"Skin Specialist",
"Laser Aesthetic Practitioner",
"Laser Therapist",
"Laser & Skin Specialist",
"Advanced Skin & Laser Therapist",
"Aesthetic/Clinic Specialist",
"Aesthetic Specialist",
"Skin Treatment Specialist",
"Skin & Beauty Consultant",
"Skin Health Practitioner",
"Skin Rejuvenation Specialist",
"Microneedling Specialist",
"Trichologist / Hair & Scalp Specialist",
"Facial Aesthetics Practitioner",
"Facial Aesthetic Clinician",
"Cosmetic Injector",
"Aesthetic Injector",
"Advanced Aesthetic Practitioner",
"Senior Aesthetician",
"Aesthetic Therapist",
"Level 4 Skin Specialist",
"Senior Skin & Laser Therapist",
"Lead Skin & Laser Therapist",
"Aesthetic Technician",
"Laser & Aesthetic Practitioner",
"Skin Care Specialist",
"Skin Care Expert",
"Beauty Therapist",
"Beautician",
"Pharmacist",
"Clinical Pharmacist & Prescriber",
"Diagnostic Radiographer",
"Midwife",
"Physiotherapist",
"Soft Tissue & Massage Specialist",
"Dental Practitioner & Facial Aesthetics Specialist",
]
   
      const locations: string[] = [
        "Altrincham",
        "Dunfermline",
        "London",
        "Royal",
        "Luton",
        "Chester",
        "Potters",
        "Brighton",
        "Liverpool",
        "Glasgow",
        "Chislehurst",
        "Bath",
        "Beaconsfield",
        "Hampton",
        "Leeds",
        "Swansea",
        "Southampton",
        "Doncaster",
        "Richmond",
        "Berkhamsted",
        "York",
        "Enfield",
        "Milton",
        "Ebbw",
        "Bathgate",
        "Llanfairpwllgwyngyll",
        "Stoke-on-Trent",
        "Swindon",
        "Sutton",
        "Tarporley",
        "Portsmouth",
        "Solihull",
        "Barnet",
        "Birmingham",
        "Woodford",
        "Manchester",
        "Middlesbrough",
        "Wilmslow",
        "Congleton",
        "Newry",
        "Edinburgh",
        "Southsea",
        "Perth",
        "Aberystwyth",
        "Warrington",
        "Littlehampton",
        "Belfast",
        "Bradford",
        "Nottingham",
        "Canterbury",
        "Plymouth",
        "Sheffield",
        "Bromley",
        "Twickenham",
        "Slough",
        "Huddersfield",
        "Tunbridge",
        "Bexhill-on-Sea",
        "Harrow",
        "Wingate",
        "Nantwich",
        "Oxford",
        "Harrogate",
        "Croydon",
        "Wolverhampton",
        "Derby",
        "Newtownards",
        "Marlow",
        "Newcastle",
        "Worthing",
        "Wakefield",
        "Christchurch",
        "Craigavon",
        "St",
        "Downpatrick",
        "Whitley",
        "Hartlepool",
        "Hove",
        "Marlborough",
        "Ascot",
        "Pontefract",
        "Tetbury",
        "Cambridge",
        "Cheltenham",
        "Sunderland",
        "Motherwell",
        "North",
        "Ruislip",
        "Saint",
        "Bedford",
        "Basildon",
        "Peterborough",
        "Winchester",
        "Cheadle",
        "Wirral",
        "Leicester",
        "Stockbridge",
        "Walsall",
        "Shrewsbury",
        "South",
        "Weston-super-Mare",
        "Borehamwood",
        "Hatfield",
        "Stockport",
        "Banstead",
        "Wallingford",
        "Henley-on-Thames",
        "Bolton",
        "Chichester",
        "Beverley",
        "Truro",
        "Bristol",
        "Kettering",
        "Pontypool",
        "Dudley",
        "Bridgnorth",
        "Halifax",
        "Colchester",
        "Hull",
        "Cottingham",
        "Northwood",
        "Buckie",
        "Durham",
        "Thornton",
        "Cardiff",
        "Salford",
        "Ilkley",
        "Yeovil",
        "Isleworth",
        "Bellshill",
        "Preston",
        "Cockermouth",
        "Bangor",
        "Sale",
        "Wrexham",
        "Bournemouth",
        "Brentford",
        "Bury",
        "Knaresborough",
        "Reading",
        "Ryde",
        "Epsom",
        "Windsor",
        "Kingston",
        "Bridgend",
        "Peacehaven",
        "Purfleet",
        "Uckfield",
        "Hornchurch",
        "Redcar",
        "Newport",
        "Oakham",
        "Hungerford",
        "Coventry",
        "Stevenage",
        "Stratford-upon-Avon",
        "Drumquin",
        "Irvine",
        "Wells",
        "Wembley",
        "Crewe",
        "Brierley",
        "Poole",
        "Chipping",
        "Alloa",
        "Blackburn",
        "Hamilton",
        "Chester-le-Street",
        "Didcot",
        "Westcliff-on-Sea",
        "Telford",
        "Stirling",
        "Dartford",
        "Hillsborough",
        "Cranbrook",
        "Barnsley",
        "Haywards",
        "Nailsworth",
        "Dorchester",
        "Bishopton",
        "Beckenham",
        "Stanford-le-Hope",
        "Maidenhead",
        "Cwmbran",
        "Alderley",
        "Rochester",
        "Arundel",
        "Holywell",
        "Haverfordwest",
        "Biggleswade",
        "Gerrards",
        "Knutsford",
        "Romford",
        "Llandysul",
        "Stanmore",
        "Boness",
        "Pinner",
        "Brentwood",
        "Bracknell",
        "Hounslow",
        "Gillingham",
        "Clitheroe",
        "Ayr",
        "Aberdeen",
        "Kinross",
        "Teddington",
        "Caernarfon",
        "Alfreton",
        "Cowes",
        "Stockton-on-Tees",
        "Kirkwall",
        "Shefford",
        "Londonderry",
        "Cleckheaton",
        "Great",
        "Seaham",
        "Dunblane",
        "Crowborough",
        "Wokingham",
        "Leamington",
        "Chesham",
        "Gravesend",
        "Enniskillen",
        "Bargoed",
        "Northwich",
        "Brough",
        "Cumnock",
        "Omagh",
        "Inverness",
        "Newbury",
        "Saltburn-by-the-Sea",
        "Dunstable",
        "Ilford",
        "Gainsborough",
        "Girvan",
        "Uxbridge",
        "Ballymena",
        "Kilmarnock",
        "Lisburn",
        "Newmarket",
        "Rotherham",
        "Melksham",
        "Wishaw",
        "Grimsby",
        "Horley",
        "Southall",
        "Tyn-y-Gongl",
        "Alderminster",
        "Gloucester",
        "Neath",
        "Wimborne",
        "Coulsdon",
        "West",
        "Hereford",
        "Ashford",
        "Gateshead",
        "St.",
        "EMCRF",
        "Caerphilly",
        "Hitchin",
        "Shotts",
        "The",
        "Southend-on-Sea",
        "Basingstoke",
        "Middlewich",
        "Huntingdon",
        "Lytham",
        "Wood",
        "Bedfordshire",
        "Purley",
        "Antrim",
        "Chelmsford",
        "Yarm",
        "Abingdon",
        "Prestonpans",
        "Farnham",
        "Livingston",
        "Lanark",
        "Limavady",
        "Peterculter",
        "Kidwelly",
        "Wetherby",
        "Worcester",
        "Longfield",
        "Paignton",
        "Burton-on-Trent",
        "Exeter",
        "Bromsgrove",
        "Esher",
        "Bishops",
        "Torquay",
        "Oldham",
        "Tavistock",
        "Fareham",
        "Maidstone",
        "Barnstaple",
        "Castleford",
        "Eastleigh",
        "Berwick-upon-Tweed",
        "Insch",
        "Ormskirk",
        "Rossendale",
        "Clacton-on-Sea",
        "Swanscombe",
        "Prestwick",
        "Daventry",
        "Wantage",
        "ELY",
        "Wigan",
        "Herne",
        "Benfleet",
        "Evesham",
        "Lewes",
        "Newark",
        "Shifnal",
        "Birkenhead",
        "Spalding",
        "Northampton",
        "Chesterfield",
        "Witham",
        "Mansfield",
        "Heathfield",
        "Wadebridge",
        "Hexham",
        "Norwich",
        "Carrickfergus",
        "Workington",
        "Weymouth",
        "Guildford",
        "Tipton",
        "Tamworth",
        "Corsham",
        "Darlington",
        "Bedale",
        "Stourbridge",
        "East",
        "Crawley",
        "Spennymoor",
        "Pickering",
        "Stafford",
        "Macclesfield",
        "Shoreham-by-Sea",
        "Horsham",
        "Hailsham",
        "Holmfirth",
        "Orpington",
        "Peterlee",
        "Hinckley",
        "Wallasey",
        "Greenhithe",
        "Stroud",
        "High",
        "Isle",
        "Upminster",
        "Dundee",
        "Lancaster",
        "Ipswich",
        "Hemel",
        "Taunton",
        "Burnley",
        "Margate",
        "Bengaluru",
        "Whitstable",
        "Magherafelt"
    ]

      set({
        clinics,
        practitioners,
        categories,
        modalities,
        professions,
        locations,
        loading: false,
        initialized: true,
        error: undefined,
      });

      console.log("✅ DataStore: Successfully populated");
    } catch (err: any) {
      console.error("❌ DataStore: Failed to fetch data:", err);
      set({
        loading: false,
        error: err.message || "Failed to load data",
      });
    }
  },
}));