import Link from "next/link"
import { Mail, Phone } from "lucide-react"
import { Button } from "@/components/ui/button"
import { modalities,edu,accreditations } from "@/lib/data";
const cityList = ["Aberaeron",
"Aberdare",
"Aberdeen",
"Aberfeldy",
"Abergavenny",
"Abergele",
"Aberpwll",
"Abertillery",
"Aberystwyth",
"Abingdon",
"Accrington",
"Airdrie",
"Alderley",
"Alderminster",
"Alexandria",
"Alfreton",
"Alloa",
"Alton",
"Altrincham",
"Alva",
"Anlaby",
"Antrim",
"Arbroath",
"Armagh",
"Arundel",
"Ascot",
"Ashford",
"Ashton-under-Lyne",
"Astwood",
"Aughnacloy",
"Avon",
"Axbridge",
"Aylesbury",
"Ayr",
"Bacup",
"Bala",
"Ballycastle",
"Ballyclare",
"Ballymena",
"Ballymoney",
"Ballynahinch",
"Banbridge",
"Banchory",
"Bangor",
"Banstead",
"Banwell",
"Bargoed",
"Barking",
"Barnet",
"Barnoldswick",
"Barnsley",
"Barrow-upon-Humber",
"Barry",
"Barton-upon-Humber",
"Basildon",
"Basingstoke",
"Bath",
"Bathgate",
"Batley",
"Battle",
"Beaconsfield",
"Bebington",
"Beckenham",
"Bedale",
"Bedford",
"Bedfordshire",
"Beds",
"Bedworth",
"Belfast",
"Bellshill",
"Belper",
"Bembridge",
"Benfleet",
"Berkhamsted",
"Berwick-upon-Tweed",
"Beverley",
"Bexhill-on-Sea",
"Bexley",
"Bexleyheath",
"Biggar",
"Biggleswade",
"Billericay",
"Billingham",
"Bilston",
"Bingley",
"Birkenhead",
"Birmingham",
"Bishop",
"Bishopton",
"Blackburn",
"Blackpool",
"Blackwood",
"Blaenau",
"Blairgowrie",
"Blyth",
"Bodorgan",
"Boldon",
"Bolton",
"Bo'ness",
"Bonnybridge",
"Bonnyrigg",
"Bootle",
"Borehamwood",
"Borth",
"Boston",
"Bournemouth",
"BOXSTART",
"Bracknell",
"Bradford",
"Brechin",
"Brentford",
"Brentwood",
"Bretton",
"Bridge",
"Bridgend",
"Bridgnorth",
"Bridgwater",
"Brierley",
"Brigg",
"Brighouse",
"Brighton",
"Brinkworth",
"Bristol",
"Broadstone",
"Bromley",
"Bromsgrove",
"Brough",
"Broughshane",
"Broughton",
"Broxburn",
"Bryngwran",
"Buckie",
"Buckingham",
"Buckley",
"Burgess",
"Burnley",
"Burton-on-Trent",
"Bury",
"Bushey",
"Caernarfon",
"Caerphilly",
"Caldicot",
"Callander",
"Callington",
"Cambridge",
"Canford",
"Canterbury",
"Cardiff",
"Cardigan",
"Carmarthen",
"Carmarthenshire",
"Carnoustie",
"Carrickfergus",
"Carshalton",
"Castlederg",
"Castleford",
"Castlewellan",
"Chalfont",
"Chatham",
"Cheadle",
"Chelmsford",
"Cheltenham",
"Chepstow",
"Chesham",
"Chester",
"Chesterfield",
"Chester-le-Street",
"Chichester",
"Chigwell",
"Chippenham",
"Chipping",
"Chislehurst",
"Chorley",
"Christchurch",
"Cirencester",
"Clackmannan",
"Cleckheaton",
"Cleethorpes",
"Clevedon",
"Clitheroe",
"Clogher",
"Clydebank",
"Coatbridge",
"Cockermouth",
"Colchester",
"Coleraine",
"Colne",
"Colwyn",
"Congleton",
"Connah's",
"Consett",
"Conwy",
"Cookstown",
"Corby",
"Cornwall",
"Corwen",
"Cottingham",
"Coulsdon",
"Coventry",
"Cowbridge",
"Cowes",
"Cradley",
"Craigavon",
"Cramlington",
"Cranbrook",
"Crawley",
"Crewe",
"Crook",
"Cross",
"Crowborough",
"Crowthorne",
"Croydon",
"Crumlin",
"Cumnock",
"Cwmbran",
"Dagenham",
"Dalkeith",
"Dalry",
"Darlington",
"Dartford",
"Darvel",
"Darwen",
"Deeside",
"Denbigh",
"Denny",
"Derby",
"Dereham",
"Devizes",
"Dewsbury",
"Didcot",
"Dinas",
"Dolgellau",
"Dollar",
"Doncaster",
"Dorchester",
"Downpatrick",
"Driffield",
"Drumquin",
"Dudley",
"Dukinfield",
"Dumbarton",
"Dumfries",
"Dunbar",
"Dunblane",
"Dundee",
"Dunfermline",
"Dungannon",
"Dunoon",
"Dunstable",
"Durham",
"Ealing",
"East",
"Eastbourne",
"Eastleigh",
"Ebbw",
"Edgware",
"Edinburgh",
"Elgin",
"Elland",
"Ellesmere",
"ELY",
"EMCRF",
"Enfield",
"Enniskillen",
"Epsom",
"Erith",
"Everlast",
"Falkirk",
"Falmouth",
"Fareham",
"Farnborough",
"Farnham",
"Ferryhill",
"Flint",
"Fochabers",
"Forest",
"Forfar",
"Forres",
"Frampton",
"Freshwater",
"Frodsham",
"Gaerwen",
"Gainsborough",
"Gateshead",
"Gerrards",
"Gillingham",
"Girvan",
"Glasgow",
"Glenrothes",
"Glossop",
"Gloucester",
"Goole",
"Gorebridge",
"Gourock",
"Grangemouth",
"Gravesend",
"Grays",
"Great",
"Greenhithe",
"Greenock",
"Grimsby",
"Guisborough",
"Gullane",
"Gwynedd",
"Haddington",
"Hailsham",
"Halesowen",
"Halifax",
"Hamilton",
"Hampton",
"Harlow",
"Harpenden",
"Harrogate",
"Harrow",
"Hartlepool",
"Hassocks",
"Hastings",
"Hatfield",
"Havant",
"Haverfordwest",
"Hawick",
"Hayes",
"Haywards",
"HBTherapy",
"Heanor",
"Heathfield",
"Hebden",
"Helensburgh",
"Helston",
"Hemel",
"Hengoed",
"Henley-on-Thames",
"Henlow",
"Hereford",
"Hertford",
"Hessle",
"Heywood",
"High",
"Hillsborough",
"Hitchin",
"hollow",
"Holmfirth",
"Holyhead",
"Holywell",
"Holywood",
"Horley",
"Hornchurch",
"Horsham",
"Houghton",
"Hounslow",
"Hove",
"Hoylake",
"Huddersfield",
"Hull",
"Hungerford",
"Huntingdon",
"Hyde",
"Ilford",
"Ilkley",
"Immingham",
"Inverness",
"Irvine",
"Isle",
"Isleworth",
"Jarrow",
"Keighley",
"Keith",
"Kelso",
"Kenilworth",
"Kent",
"Keston",
"Kettering",
"Kilgetty",
"Kilmacolm",
"Kilmarnock",
"Kilrea",
"Kilsyth",
"Kilwinning",
"Kings",
"Kingston",
"Kinross",
"Kirkcaldy",
"Kirkwall",
"Kirriemuir",
"Knaresborough",
"Knottingley",
"Knutsford",
"Lampeter",
"Lanark",
"Lancaster",
"Larbert",
"Larkhall",
"Larne",
"Latchmeads",
"Lauder",
"Launceston",
"Leamington",
"Leeds",
"Leicester",
"Leicestershire",
"Leigh",
"Leigh-on-Sea",
"Leighton",
"Letchworth",
"Lewes",
"Leyland",
"Limavady",
"Lincoln",
"Linlithgow",
"Lisburn",
"Liskeard",
"Littleborough",
"Littlehampton",
"Liverpool",
"Liversedge",
"Livingston",
"Llandrindod",
"Llandudno",
"Llandysul",
"Llanelli",
"Llanfairfechan",
"Llanfairpwllgwyngyll",
"Llangefni",
"Llangollen",
"Llannerch-y-medd",
"Llanrwst",
"Llanybydder",
"Loanhead",
"London",
"Londonderry",
"Longhope",
"Lossiemouth",
"Lostwithiel",
"Loughborough",
"Luton",
"Lydney",
"Lymm",
"Lytham",
"Macclesfield",
"Maesteg",
"Maghera",
"Magherafelt",
"Maidenhead",
"Maidstone",
"Maldon",
"Malmesbury",
"Manchester",
"Marlborough",
"Marlow",
"Matlock",
"Mauchline",
"Maulden",
"Mayfield",
"Melksham",
"Melrose",
"Melton",
"Menai",
"Merseyside",
"Merthyr",
"Mexborough",
"Middlesbrough",
"Middlewich",
"Milton",
"Mirfield",
"Mitcham",
"Moffat",
"Mold",
"Monmouth",
"Montrose",
"Morpeth",
"Motherwell",
"Mountain",
"Much",
"Musselburgh",
"Nailsworth",
"Nantwich",
"Narberth",
"Neath",
"Nelson",
"New",
"Newbury",
"Newcastle",
"Newcastle-under-Lyme",
"Newhaven",
"Newmarket",
"Newmilns",
"Newport",
"Newquay",
"Newry",
"Newton",
"Newton-le-Willows",
"Newtownabbey",
"Newtownards",
"Newtownstewart",
"Ninewells",
"Normanton",
"North",
"Northampton",
"Northwich",
"Northwood",
"Norwich",
"Nottingham",
"Oakham",
"Oldbury",
"Oldham",
"Omagh",
"Orkney",
"Ormskirk",
"Orpington",
"Ossett",
"Oswestry",
"Otley",
"Oxford",
"Paisley",
"parking",
"Pathhead",
"Peacehaven",
"Peasedown",
"Pembroke",
"Penarth",
"Pentraeth",
"Penzance",
"Perth",
"Peterborough",
"Peterculter",
"Peterlee",
"Pinner",
"Plymouth",
"Pontefract",
"Pontyclun",
"Pontypool",
"Pontypridd",
"Poole",
"Port",
"Porth",
"Porthcawl",
"Porthmadog",
"Portsmouth",
"Portstewart",
"Potters",
"Poulton-le-Fylde",
"Prescot",
"Prestatyn",
"Preston",
"Prestonpans",
"Prestwick",
"Pudsey",
"Purfleet",
"Purley",
"Pwllheli",
"Radstock",
"Rainford",
"Rainham",
"Rayleigh",
"Reading",
"Redcar",
"Redruth",
"Renfrew",
"Rhosneigr",
"Rhyl",
"Richmond",
"Ringwood",
"Robertsbridge",
"Rochdale",
"Rochester",
"Romford",
"Romsey",
"Rossendale",
"Ross-on-Wye",
"Rotherham",
"Rowlands",
"Royal",
"Rugby",
"Ruislip",
"Runcorn",
"Ruthin",
"Ryde",
"Rye",
"Saint",
"Sale",
"Salford",
"Salisbury",
"Saltburn-by-the-Sea",
"Saltcoats",
"Sandbach",
"Sandown",
"Scunthorpe",
"Seaford",
"Seaham",
"Selby",
"Sevenoaks",
"Shanklin",
"Sheffield",
"Shefford",
"Shetland",
"Shipley",
"Shoreham-by-Sea",
"Shotts",
"Shrewsbury",
"Sidcup",
"Silsoe",
"Sittingbourne",
"Skegness",
"Skelmorlie",
"Skipton",
"Slough",
"Smethwick",
"Snodland",
"Solihull",
"South",
"Southall",
"Southampton",
"Southend-on-Sea",
"Southport",
"Southsea",
"Sowerby",
"Spilsby",
"St",
"St.",
"Stafford",
"Staines",
"Stalybridge",
"Stamford",
"Stanford-le-Hope",
"Stanley",
"Stanmore",
"Stevenage",
"Stirling",
"Stockbridge",
"Stockport",
"Stockton-on-Tees",
"Stoke-on-Trent",
"Stornoway",
"Stourbridge",
"Strabane",
"Stranraer",
"Stratford-upon-Avon",
"Strathaven",
"Stretford",
"Stromness",
"Stroud",
"Sunderland",
"Surbiton",
"Sutton",
"Swadlincote",
"Swansea",
"Swindon",
"Symington",
"Tarbert",
"Tarporley",
"Teddington",
"Telford",
"Tetbury",
"Thatcham",
"The",
"Thornton",
"Thornton-Cleveleys",
"Thurrock",
"Tipton",
"Todmorden",
"Tonbridge",
"Tonypandy",
"Topiary",
"Totland",
"Tranent",
"Treorchy",
"Trimdon",
"Troon",
"Trowbridge",
"Truro",
"Tunbridge",
"Twickenham",
"Tyn-y-Gongl",
"Uckfield",
"UK",
"Ulceby",
"Upminster",
"Uxbridge",
"Ventnor",
"Wakefield",
"Wallasey",
"Wallingford",
"Wallington",
"Wallsend",
"Walsall",
"Ware",
"Warlingham",
"Warrington",
"Warwick",
"Washington",
"Waterlooville",
"Wednesbury",
"Welling",
"Wells",
"Wembley",
"Wemyss",
"West",
"Westbury",
"Westcliff-on-Sea",
"Westerham",
"Westhill",
"Weston-super-Mare",
"Wetherby",
"Wexham",
"Whitchurch",
"Whitehaven",
"Whitley",
"Whitstable",
"Wickford",
"Widnes",
"Wigan",
"Wigston",
"Willenhall",
"Wilmslow",
"Wimborne",
"Winchester",
"Windsor",
"Wingate",
"Winscombe",
"Winsford",
"Wirral",
"Wishaw",
"Witham",
"WN58RR",
"Wokingham",
"Wolverhampton",
"Wood",
"Woodford",
"Worcester",
"Worthing",
"Wotton-under-Edge",
"Wrexham",
"Y",
"Yarm",
"Yeovil",
"York",
]

 export function Footer() {
  const recognitions = [...accreditations, ...edu]
   return (
     <>
    <footer className="bg-[var(--dune)] py-16 text-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex items-center flex-col md:flex-row justify-between">
            <div className="w-full md:w-auto">
              <h3 className="text-lg md:text-4xl font-bold mb-2">Ready To Get Started?</h3>
              <p className="">Join over 200+ clinics already growing with Consentz.</p>
            </div>
            <div className="flex justify-start w-full md:w-auto pt-10 md:pt-0">
              <Button className="h-auto rounded-lg md:text-lg px-4 py-2 md:px-5 md:py-2 bg-white text-black hover:bg-gray-200">
                BOOK DEMO
              </Button>
            </div>
          </div>
          <div className="border-t border-white my-12"></div>

          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-8 mb-12">
            {/* CONSENTZ + Contact */}
            <div>
              <div className="font-bold text-lg mb-6">
                <img src="/directory/images/Consentz Logo light.svg" alt="Logo" width={180} />
              </div>
              <h3 className="sr-only">Contact Information</h3>
              <div className="text-sm  space-y-2">
                <p className="flex items-center gap-2">
                  <Phone className="w-5 h-5 text-white mr-2 flex-shrink-0 mt-0.5" />
                  <span>[UK] +44 (0) 208 050 3372</span>
                </p>
                <p className="flex items-center gap-2">
                  <Phone className="w-5 h-5 text-white mr-2 flex-shrink-0 mt-0.5" />
                  <span>(US) +1 646 786 1949</span>
                </p>
                <p className="flex items-center gap-2">
                  <Mail className="w-5 h-5 text-white mr-2 flex-shrink-0 mt-0.5" />
                  <span>contact@consentz.com</span>
                </p>
              </div>
            </div>

            {/* Consentz vs Column */}
            <div>
              <h3 className="font-bold text-lg text-white mb-6">Consentz vs</h3>
              <ul className="space-y-3 text-sm">
                <li><button className="text-left w-full hover:text-white transition" type="button">Zenoti</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">AestheticsPro</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Pabau</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Aesthetic Record</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">ClinicsEnse</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Nextech</button></li>
              </ul>
            </div>

            {/* Features Column */}
            <div>
              <h3 className="font-bold text-lg text-white mb-6">Features</h3>
              <ul className="space-y-3 text-sm">
                <li><button className="text-left w-full hover:text-white transition" type="button">Clinic Management</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Patient Engagement</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Photos and Records</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Personalise</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Analytics</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Stock and Billing</button></li>
              </ul>
            </div>

            {/* Marketing Column */}
            <div>
              <h3 className="font-bold text-lg text-white mb-6">Marketing</h3>
              <ul className="space-y-3 text-sm">
                <li><button className="text-left w-full hover:text-white transition" type="button">FAQs</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Blog</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Articles</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Support</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Terms & Conditions</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Partners</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Privacy Policy</button></li>
              </ul>
            </div>

            {/* Get the App Column */}
            <div>
              <h3 className="font-bold text-lg text-white mb-6">Get the app</h3>
              <div className="">
                <img src="/directory/images/Consentz Iphone App.webp" alt="" width={139} />
              </div>
            </div>
          </div>

          <div className="border-t border-white my-8"></div>

          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-8 text-sm">
            {/* Column 1: Description */}
            <div>
              <h3 className="sr-only">About the Directory</h3>
              <p className="font-bold text-white mb-3">Find qualified healthcare and aesthetic practitioners in your area. Verified profiles, authentic reviews, and regulatory compliance.</p>
            </div>

             {/* Column 2: Clinics */}
             {/* Quick Links */}
             <div className="space-y-4">
             <h4 className="font-semibold">Clinics</h4>
             <ul className="gap-4 max-h-[100px] overflow-auto">
              {cityList.map((city, index) => (
                <li key={index}>
                  <Link href={`/clinics/${city}`} className="block text-sm">
                    Top Clinics in {city}
                  </Link>
                </li>
               ))}
             </ul>
              <h4 className="font-semibold">Treatments</h4>
              <ul className="gap-4 max-h-[100px] overflow-auto">
              {modalities.map((t, index_t) => (
                <li key={index_t}>
                  <Link href={`/clinics/London/services/${t}`} className="block text-sm">
                    {t}
                  </Link>
                </li>
              ))}
            </ul>
            <h4 className="font-semibold">Accredited Practitioners</h4>
              <ul className="gap-4 max-h-[100px] overflow-auto">
              {recognitions.map((t, index_t) => (
                <li key={index_t}>
                  <Link href={`/practitioners/credentials/${t}`} className="block text-sm">
                    {t}
                  </Link>
                </li>
              ))}
            </ul>
            </div>

            {/* Column 3: For Practitioners */}
            <div>
              <h4 className="font-bold text-white mb-4">For Practitioners</h4>
              <ul className="space-y-2">
                <li><button className="text-left w-full hover:text-white transition" type="button">Join Directory</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Update Profile</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Verification Process</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Support</button></li>
              </ul>
            </div>

            {/* Column 4: Contact */}
            <div>
              <h4 className="font-bold text-white mb-4">Contact</h4>
              <ul className="space-y-2">
                <li><button className="text-left w-full hover:text-white transition" type="button">Info@healthdirectory.com</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">+44 208 050 3372</button></li>
                <li><button className="text-left w-full hover:text-white transition" type="button">Contact@consentz.com</button></li>
              </ul>
            </div>

            {/* Column 4: Contact */}
            <div>
              <h4 className="font-bold text-white mb-4">Contact</h4>
              <ul className="space-y-2">
                <li><div className="hover:text-white transition">Info@healthdirectory.com</div></li>
                <li><div className="hover:text-white transition">+44 208 050 3372</div></li>
                <li><div className="hover:text-white transition">Contact@consentz.com</div></li>
              </ul>
            </div>
           </div>
         </div>
    </footer>
      </>


      
)
}